// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: activity.sql

package sqlc

import (
	"context"
	"time"
)

const getLastUserActivityAt = `-- name: GetLastUserActivityAt :one
SELECT last_seen_at
FROM user_daily_activity
WHERE user_id = ?
ORDER BY last_seen_at DESC
LIMIT 1
`

func (q *Queries) GetLastUserActivityAt(ctx context.Context, userID string) (time.Time, error) {
	row := q.db.QueryRowContext(ctx, getLastUserActivityAt, userID)
	var last_seen_at time.Time
	err := row.Scan(&last_seen_at)
	return last_seen_at, err
}

const listUserDailyActivity = `-- name: ListUserDailyActivity :many
SELECT
    day,
    hit_count,
    last_seen_at
FROM user_daily_activity
WHERE user_id = ?
  AND day >= ?
  AND day < ?
ORDER BY day ASC
`

type ListUserDailyActivityParams struct {
	UserID string `json:"user_id"`
	Day    string `json:"day"`
	Day_2  string `json:"day_2"`
}

type ListUserDailyActivityRow struct {
	Day        string    `json:"day"`
	HitCount   int64     `json:"hit_count"`
	LastSeenAt time.Time `json:"last_seen_at"`
}

func (q *Queries) ListUserDailyActivity(ctx context.Context, arg ListUserDailyActivityParams) ([]ListUserDailyActivityRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserDailyActivity, arg.UserID, arg.Day, arg.Day_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserDailyActivityRow{}
	for rows.Next() {
		var i ListUserDailyActivityRow
		if err := rows.Scan(&i.Day, &i.HitCount, &i.LastSeenAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertUserDailyActivity = `-- name: UpsertUserDailyActivity :exec
INSERT INTO user_daily_activity (
    user_id,
    day,
    first_seen_at,
    last_seen_at,
    hit_count
) VALUES (?, ?, ?, ?, 1)
ON CONFLICT(user_id, day) DO UPDATE SET
    first_seen_at = MIN(user_daily_activity.first_seen_at, excluded.first_seen_at),
    last_seen_at = MAX(user_daily_activity.last_seen_at, excluded.last_seen_at),
    hit_count = CASE
        WHEN user_daily_activity.last_seen_at < sqlc.arg(dedupe_cutoff) THEN user_daily_activity.hit_count + 1
        ELSE user_daily_activity.hit_count
    END
`

type UpsertUserDailyActivityParams struct {
	UserID      string    `json:"user_id"`
	Day         string    `json:"day"`
	FirstSeenAt time.Time `json:"first_seen_at"`
	LastSeenAt  time.Time `json:"last_seen_at"`
}

func (q *Queries) UpsertUserDailyActivity(ctx context.Context, arg UpsertUserDailyActivityParams) error {
	_, err := q.db.ExecContext(ctx, upsertUserDailyActivity,
		arg.UserID,
		arg.Day,
		arg.FirstSeenAt,
		arg.LastSeenAt,
	)
	return err
}
