// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countActiveUsers = `-- name: CountActiveUsers :one
SELECT COUNT(*) FROM users
WHERE subscription_status IN ('active', 'trialing', 'on_trial')
OR is_founding_member = 1
OR (has_beta_access = 1 AND (beta_expires_at IS NULL OR beta_expires_at > datetime('now')))
`

func (q *Queries) CountActiveUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAdminUsers = `-- name: CountAdminUsers :one
SELECT COUNT(*) FROM local_credentials WHERE is_admin = 1
`

func (q *Queries) CountAdminUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAdminUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAllUsers = `-- name: CountAllUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountAllUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAllUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countBetaUsers = `-- name: CountBetaUsers :one
SELECT COUNT(*) FROM users
WHERE has_beta_access = 1
`

func (q *Queries) CountBetaUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countBetaUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFoundingMembers = `-- name: CountFoundingMembers :one
SELECT COUNT(*) FROM users
WHERE is_founding_member = 1
`

func (q *Queries) CountFoundingMembers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFoundingMembers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLocalAccounts = `-- name: CountLocalAccounts :one

SELECT COUNT(*) FROM local_credentials
`

// Self-host admin queries
func (q *Queries) CountLocalAccounts(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countLocalAccounts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMasterPasswordUsers = `-- name: CountMasterPasswordUsers :one
SELECT COUNT(*) FROM users WHERE is_master_password_set = 1
`

func (q *Queries) CountMasterPasswordUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMasterPasswordUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMemberships = `-- name: CountMemberships :one
SELECT COUNT(*) FROM budget_space_members
`

func (q *Queries) CountMemberships(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMemberships)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPaidUsers = `-- name: CountPaidUsers :one
SELECT COUNT(*) FROM users
WHERE subscription_status = 'active'
`

func (q *Queries) CountPaidUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPaidUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPendingInvites = `-- name: CountPendingInvites :one
SELECT COUNT(*) FROM budget_space_invites WHERE status = 'pending'
`

func (q *Queries) CountPendingInvites(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPendingInvites)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSpaces = `-- name: CountSpaces :one
SELECT COUNT(*) FROM budget_spaces
`

func (q *Queries) CountSpaces(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSpaces)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSpacesWithMembers = `-- name: CountSpacesWithMembers :one
SELECT COUNT(DISTINCT space_id) FROM budget_space_members
`

func (q *Queries) CountSpacesWithMembers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSpacesWithMembers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTrialUsers = `-- name: CountTrialUsers :one
SELECT COUNT(*) FROM users
WHERE subscription_status IN ('trialing', 'on_trial')
`

func (q *Queries) CountTrialUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTrialUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSavedQuery = `-- name: CreateSavedQuery :one
INSERT INTO saved_queries (name, query)
VALUES (?, ?)
RETURNING id, name, query, created_at, updated_at
`

type CreateSavedQueryParams struct {
	Name  string `json:"name"`
	Query string `json:"query"`
}

func (q *Queries) CreateSavedQuery(ctx context.Context, arg CreateSavedQueryParams) (SavedQuery, error) {
	row := q.db.QueryRowContext(ctx, createSavedQuery, arg.Name, arg.Query)
	var i SavedQuery
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Query,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSavedQuery = `-- name: DeleteSavedQuery :exec
DELETE FROM saved_queries WHERE name = ?
`

func (q *Queries) DeleteSavedQuery(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteSavedQuery, name)
	return err
}

const getSavedQueryByName = `-- name: GetSavedQueryByName :one
SELECT id, name, query, created_at, updated_at
FROM saved_queries
WHERE name = ?
`

func (q *Queries) GetSavedQueryByName(ctx context.Context, name string) (SavedQuery, error) {
	row := q.db.QueryRowContext(ctx, getSavedQueryByName, name)
	var i SavedQuery
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Query,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserForAdmin = `-- name: GetUserForAdmin :one
SELECT
       u.id, u.name, u.email, u.created_at,
       c.last_login_at,
       subscription_status, subscription_id, customer_id, variant_id,
       subscription_ends_at, trial_ends_at, current_period_end,
       has_beta_access, beta_expires_at, is_founding_member,
       is_master_password_set, has_collaboration_access, is_blocked,
       COALESCE(c.is_admin, 0) AS is_admin
FROM users u
LEFT JOIN local_credentials c ON c.user_id = u.id
WHERE u.id = ?
LIMIT 1
`

type GetUserForAdminRow struct {
	ID                     string         `json:"id"`
	Name                   string         `json:"name"`
	Email                  string         `json:"email"`
	CreatedAt              sql.NullTime   `json:"created_at"`
	LastLoginAt            sql.NullTime   `json:"last_login_at"`
	SubscriptionStatus     sql.NullString `json:"subscription_status"`
	SubscriptionID         sql.NullString `json:"subscription_id"`
	CustomerID             sql.NullString `json:"customer_id"`
	VariantID              sql.NullString `json:"variant_id"`
	SubscriptionEndsAt     sql.NullTime   `json:"subscription_ends_at"`
	TrialEndsAt            sql.NullTime   `json:"trial_ends_at"`
	CurrentPeriodEnd       sql.NullTime   `json:"current_period_end"`
	HasBetaAccess          bool           `json:"has_beta_access"`
	BetaExpiresAt          sql.NullTime   `json:"beta_expires_at"`
	IsFoundingMember       bool           `json:"is_founding_member"`
	IsMasterPasswordSet    bool           `json:"is_master_password_set"`
	HasCollaborationAccess bool           `json:"has_collaboration_access"`
	IsBlocked              bool           `json:"is_blocked"`
	IsAdmin                bool           `json:"is_admin"`
}

func (q *Queries) GetUserForAdmin(ctx context.Context, id string) (GetUserForAdminRow, error) {
	row := q.db.QueryRowContext(ctx, getUserForAdmin, id)
	var i GetUserForAdminRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.CreatedAt,
		&i.LastLoginAt,
		&i.SubscriptionStatus,
		&i.SubscriptionID,
		&i.CustomerID,
		&i.VariantID,
		&i.SubscriptionEndsAt,
		&i.TrialEndsAt,
		&i.CurrentPeriodEnd,
		&i.HasBetaAccess,
		&i.BetaExpiresAt,
		&i.IsFoundingMember,
		&i.IsMasterPasswordSet,
		&i.HasCollaborationAccess,
		&i.IsBlocked,
		&i.IsAdmin,
	)
	return i, err
}

const listRecentUsers = `-- name: ListRecentUsers :many
SELECT id, name, email, created_at
FROM users
ORDER BY created_at DESC
LIMIT 5
`

type ListRecentUsersRow struct {
	ID        string       `json:"id"`
	Name      string       `json:"name"`
	Email     string       `json:"email"`
	CreatedAt sql.NullTime `json:"created_at"`
}

func (q *Queries) ListRecentUsers(ctx context.Context) ([]ListRecentUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecentUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentUsersRow{}
	for rows.Next() {
		var i ListRecentUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSavedQueries = `-- name: ListSavedQueries :many

SELECT id, name, query, created_at, updated_at
FROM saved_queries
ORDER BY name ASC
`

// Saved queries for database explorer
func (q *Queries) ListSavedQueries(ctx context.Context) ([]SavedQuery, error) {
	rows, err := q.db.QueryContext(ctx, listSavedQueries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SavedQuery{}
	for rows.Next() {
		var i SavedQuery
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Query,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSelfHostUsers = `-- name: ListSelfHostUsers :many
SELECT
    u.id,
    u.name,
    u.email,
    u.created_at,
    u.is_master_password_set,
    u.is_blocked,
    c.last_login_at,
    COALESCE(c.is_admin, 0) AS is_admin,
    CASE WHEN c.user_id IS NOT NULL THEN 1 ELSE 0 END AS has_local_password,
    (SELECT COUNT(*) FROM budget_space_members m WHERE m.user_id = u.id) AS membership_count,
    (SELECT COUNT(*) FROM budget_spaces s WHERE s.owner_user_id = u.id) AS owned_space_count
FROM users u
LEFT JOIN local_credentials c ON c.user_id = u.id
ORDER BY u.created_at DESC
`

type ListSelfHostUsersRow struct {
	ID                  string       `json:"id"`
	Name                string       `json:"name"`
	Email               string       `json:"email"`
	CreatedAt           sql.NullTime `json:"created_at"`
	IsMasterPasswordSet bool         `json:"is_master_password_set"`
	IsBlocked           bool         `json:"is_blocked"`
	LastLoginAt         sql.NullTime `json:"last_login_at"`
	IsAdmin             bool         `json:"is_admin"`
	HasLocalPassword    int64        `json:"has_local_password"`
	MembershipCount     int64        `json:"membership_count"`
	OwnedSpaceCount     int64        `json:"owned_space_count"`
}

func (q *Queries) ListSelfHostUsers(ctx context.Context) ([]ListSelfHostUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listSelfHostUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSelfHostUsersRow{}
	for rows.Next() {
		var i ListSelfHostUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.CreatedAt,
			&i.IsMasterPasswordSet,
			&i.IsBlocked,
			&i.LastLoginAt,
			&i.IsAdmin,
			&i.HasLocalPassword,
			&i.MembershipCount,
			&i.OwnedSpaceCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersForAdmin = `-- name: ListUsersForAdmin :many
SELECT
       u.id, u.name, u.email, u.created_at,
       c.last_login_at,
       subscription_status, subscription_id, customer_id, variant_id,
       subscription_ends_at, trial_ends_at, current_period_end,
       has_beta_access, beta_expires_at, is_founding_member,
       is_master_password_set, has_collaboration_access, is_blocked,
       COALESCE(c.is_admin, 0) AS is_admin
FROM users u
LEFT JOIN local_credentials c ON c.user_id = u.id
ORDER BY u.created_at DESC
`

type ListUsersForAdminRow struct {
	ID                     string         `json:"id"`
	Name                   string         `json:"name"`
	Email                  string         `json:"email"`
	CreatedAt              sql.NullTime   `json:"created_at"`
	LastLoginAt            sql.NullTime   `json:"last_login_at"`
	SubscriptionStatus     sql.NullString `json:"subscription_status"`
	SubscriptionID         sql.NullString `json:"subscription_id"`
	CustomerID             sql.NullString `json:"customer_id"`
	VariantID              sql.NullString `json:"variant_id"`
	SubscriptionEndsAt     sql.NullTime   `json:"subscription_ends_at"`
	TrialEndsAt            sql.NullTime   `json:"trial_ends_at"`
	CurrentPeriodEnd       sql.NullTime   `json:"current_period_end"`
	HasBetaAccess          bool           `json:"has_beta_access"`
	BetaExpiresAt          sql.NullTime   `json:"beta_expires_at"`
	IsFoundingMember       bool           `json:"is_founding_member"`
	IsMasterPasswordSet    bool           `json:"is_master_password_set"`
	HasCollaborationAccess bool           `json:"has_collaboration_access"`
	IsBlocked              bool           `json:"is_blocked"`
	IsAdmin                bool           `json:"is_admin"`
}

func (q *Queries) ListUsersForAdmin(ctx context.Context) ([]ListUsersForAdminRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsersForAdmin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersForAdminRow{}
	for rows.Next() {
		var i ListUsersForAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.CreatedAt,
			&i.LastLoginAt,
			&i.SubscriptionStatus,
			&i.SubscriptionID,
			&i.CustomerID,
			&i.VariantID,
			&i.SubscriptionEndsAt,
			&i.TrialEndsAt,
			&i.CurrentPeriodEnd,
			&i.HasBetaAccess,
			&i.BetaExpiresAt,
			&i.IsFoundingMember,
			&i.IsMasterPasswordSet,
			&i.HasCollaborationAccess,
			&i.IsBlocked,
			&i.IsAdmin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersWithSubscription = `-- name: ListUsersWithSubscription :many
SELECT id, subscription_id FROM users
WHERE subscription_id IS NOT NULL AND subscription_id <> ''
`

type ListUsersWithSubscriptionRow struct {
	ID             string         `json:"id"`
	SubscriptionID sql.NullString `json:"subscription_id"`
}

func (q *Queries) ListUsersWithSubscription(ctx context.Context) ([]ListUsersWithSubscriptionRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsersWithSubscription)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersWithSubscriptionRow{}
	for rows.Next() {
		var i ListUsersWithSubscriptionRow
		if err := rows.Scan(&i.ID, &i.SubscriptionID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const migrateUserID = `-- name: MigrateUserID :exec
UPDATE users SET id = ?, name = ?, email = ? WHERE id = ?
`

type MigrateUserIDParams struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
	ID_2  string `json:"id_2"`
}

func (q *Queries) MigrateUserID(ctx context.Context, arg MigrateUserIDParams) error {
	_, err := q.db.ExecContext(ctx, migrateUserID,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.ID_2,
	)
	return err
}

const revokeAllUserAccess = `-- name: RevokeAllUserAccess :exec
UPDATE users
SET subscription_status = 'inactive',
    has_beta_access = 0,
    beta_expires_at = NULL,
    is_founding_member = 0,
    has_collaboration_access = 0
WHERE id = ?
`

func (q *Queries) RevokeAllUserAccess(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, revokeAllUserAccess, id)
	return err
}

const sumSpaceBlobBytes = `-- name: SumSpaceBlobBytes :one
SELECT COALESCE(SUM(size_bytes), 0) FROM budget_space_blobs
`

func (q *Queries) SumSpaceBlobBytes(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, sumSpaceBlobBytes)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const updateSavedQuery = `-- name: UpdateSavedQuery :exec
UPDATE saved_queries
SET query = ?, updated_at = datetime('now')
WHERE name = ?
`

type UpdateSavedQueryParams struct {
	Query string `json:"query"`
	Name  string `json:"name"`
}

func (q *Queries) UpdateSavedQuery(ctx context.Context, arg UpdateSavedQueryParams) error {
	_, err := q.db.ExecContext(ctx, updateSavedQuery, arg.Query, arg.Name)
	return err
}

const updateUserSubscriptionFull = `-- name: UpdateUserSubscriptionFull :exec
UPDATE users SET
    subscription_status = ?,
    subscription_id = ?,
    variant_id = ?,
    subscription_ends_at = ?,
    trial_ends_at = ?,
    current_period_end = ?
WHERE id = ?
`

type UpdateUserSubscriptionFullParams struct {
	SubscriptionStatus sql.NullString `json:"subscription_status"`
	SubscriptionID     sql.NullString `json:"subscription_id"`
	VariantID          sql.NullString `json:"variant_id"`
	SubscriptionEndsAt sql.NullTime   `json:"subscription_ends_at"`
	TrialEndsAt        sql.NullTime   `json:"trial_ends_at"`
	CurrentPeriodEnd   sql.NullTime   `json:"current_period_end"`
	ID                 string         `json:"id"`
}

func (q *Queries) UpdateUserSubscriptionFull(ctx context.Context, arg UpdateUserSubscriptionFullParams) error {
	_, err := q.db.ExecContext(ctx, updateUserSubscriptionFull,
		arg.SubscriptionStatus,
		arg.SubscriptionID,
		arg.VariantID,
		arg.SubscriptionEndsAt,
		arg.TrialEndsAt,
		arg.CurrentPeriodEnd,
		arg.ID,
	)
	return err
}
