// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: credentials.sql

package sqlc

import (
	"context"
)

const createLocalCredential = `-- name: CreateLocalCredential :exec
INSERT INTO local_credentials (user_id, password_hash, is_admin, created_at)
VALUES (?, ?, ?, datetime('now'))
`

type CreateLocalCredentialParams struct {
	UserID       string `json:"user_id"`
	PasswordHash string `json:"password_hash"`
	IsAdmin      bool   `json:"is_admin"`
}

func (q *Queries) CreateLocalCredential(ctx context.Context, arg CreateLocalCredentialParams) error {
	_, err := q.db.ExecContext(ctx, createLocalCredential, arg.UserID, arg.PasswordHash, arg.IsAdmin)
	return err
}

const getLocalCredential = `-- name: GetLocalCredential :one
SELECT user_id, password_hash, is_admin, last_login_at, created_at, updated_at FROM local_credentials WHERE user_id = ?
`

func (q *Queries) GetLocalCredential(ctx context.Context, userID string) (LocalCredential, error) {
	row := q.db.QueryRowContext(ctx, getLocalCredential, userID)
	var i LocalCredential
	err := row.Scan(
		&i.UserID,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const isLocalAdmin = `-- name: IsLocalAdmin :one
SELECT is_admin FROM local_credentials WHERE user_id = ?
`

func (q *Queries) IsLocalAdmin(ctx context.Context, userID string) (bool, error) {
	row := q.db.QueryRowContext(ctx, isLocalAdmin, userID)
	var is_admin bool
	err := row.Scan(&is_admin)
	return is_admin, err
}

const markLocalLogin = `-- name: MarkLocalLogin :exec
UPDATE local_credentials
SET last_login_at = datetime('now')
WHERE user_id = ?
`

func (q *Queries) MarkLocalLogin(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, markLocalLogin, userID)
	return err
}

const setLocalAdmin = `-- name: SetLocalAdmin :exec
UPDATE local_credentials
SET is_admin = ?, updated_at = datetime('now')
WHERE user_id = ?
`

type SetLocalAdminParams struct {
	IsAdmin bool   `json:"is_admin"`
	UserID  string `json:"user_id"`
}

func (q *Queries) SetLocalAdmin(ctx context.Context, arg SetLocalAdminParams) error {
	_, err := q.db.ExecContext(ctx, setLocalAdmin, arg.IsAdmin, arg.UserID)
	return err
}

const updateLocalCredentialPassword = `-- name: UpdateLocalCredentialPassword :exec
UPDATE local_credentials
SET password_hash = ?, updated_at = datetime('now')
WHERE user_id = ?
`

type UpdateLocalCredentialPasswordParams struct {
	PasswordHash string `json:"password_hash"`
	UserID       string `json:"user_id"`
}

func (q *Queries) UpdateLocalCredentialPassword(ctx context.Context, arg UpdateLocalCredentialPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateLocalCredentialPassword, arg.PasswordHash, arg.UserID)
	return err
}

const upsertLocalCredential = `-- name: UpsertLocalCredential :exec
INSERT INTO local_credentials (user_id, password_hash, is_admin, updated_at)
VALUES (?, ?, ?, datetime('now'))
ON CONFLICT(user_id) DO UPDATE SET
    password_hash = excluded.password_hash,
    is_admin = excluded.is_admin,
    updated_at = datetime('now')
`

type UpsertLocalCredentialParams struct {
	UserID       string `json:"user_id"`
	PasswordHash string `json:"password_hash"`
	IsAdmin      bool   `json:"is_admin"`
}

func (q *Queries) UpsertLocalCredential(ctx context.Context, arg UpsertLocalCredentialParams) error {
	_, err := q.db.ExecContext(ctx, upsertLocalCredential, arg.UserID, arg.PasswordHash, arg.IsAdmin)
	return err
}
