// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: exchange_rates.sql

package sqlc

import (
	"context"
)

const getExchangeRate = `-- name: GetExchangeRate :one
SELECT rate FROM exchange_rates
WHERE base_currency = ? AND target_currency = ? AND month = ?
`

type GetExchangeRateParams struct {
	BaseCurrency   string `json:"base_currency"`
	TargetCurrency string `json:"target_currency"`
	Month          string `json:"month"`
}

func (q *Queries) GetExchangeRate(ctx context.Context, arg GetExchangeRateParams) (float64, error) {
	row := q.db.QueryRowContext(ctx, getExchangeRate, arg.BaseCurrency, arg.TargetCurrency, arg.Month)
	var rate float64
	err := row.Scan(&rate)
	return rate, err
}

const listExchangeRates = `-- name: ListExchangeRates :many
SELECT base_currency, target_currency, month, rate, updated_at FROM exchange_rates
WHERE base_currency = ? AND month = ?
`

type ListExchangeRatesParams struct {
	BaseCurrency string `json:"base_currency"`
	Month        string `json:"month"`
}

func (q *Queries) ListExchangeRates(ctx context.Context, arg ListExchangeRatesParams) ([]ExchangeRate, error) {
	rows, err := q.db.QueryContext(ctx, listExchangeRates, arg.BaseCurrency, arg.Month)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExchangeRate{}
	for rows.Next() {
		var i ExchangeRate
		if err := rows.Scan(
			&i.BaseCurrency,
			&i.TargetCurrency,
			&i.Month,
			&i.Rate,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertExchangeRate = `-- name: UpsertExchangeRate :exec
INSERT INTO exchange_rates (base_currency, target_currency, month, rate, updated_at)
VALUES (?, ?, ?, ?, datetime('now'))
ON CONFLICT(base_currency, target_currency, month) DO UPDATE SET
    rate = excluded.rate,
    updated_at = datetime('now')
`

type UpsertExchangeRateParams struct {
	BaseCurrency   string  `json:"base_currency"`
	TargetCurrency string  `json:"target_currency"`
	Month          string  `json:"month"`
	Rate           float64 `json:"rate"`
}

func (q *Queries) UpsertExchangeRate(ctx context.Context, arg UpsertExchangeRateParams) error {
	_, err := q.db.ExecContext(ctx, upsertExchangeRate,
		arg.BaseCurrency,
		arg.TargetCurrency,
		arg.Month,
		arg.Rate,
	)
	return err
}
