// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
	"time"
)

type BetaInvite struct {
	Code      string         `json:"code"`
	CreatedBy string         `json:"created_by"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UsedBy    sql.NullString `json:"used_by"`
	UsedAt    sql.NullTime   `json:"used_at"`
	ExpiresAt time.Time      `json:"expires_at"`
	GrantDays int64          `json:"grant_days"`
}

type BudgetSpace struct {
	SpaceID     string       `json:"space_id"`
	OwnerUserID string       `json:"owner_user_id"`
	DisplayName string       `json:"display_name"`
	CreatedAt   time.Time    `json:"created_at"`
	UpdatedAt   sql.NullTime `json:"updated_at"`
}

type BudgetSpaceBlob struct {
	SpaceID              string    `json:"space_id"`
	BlobPath             string    `json:"blob_path"`
	CurrentHash          string    `json:"current_hash"`
	SyncVersion          int64     `json:"sync_version"`
	SizeBytes            int64     `json:"size_bytes"`
	UpdatedAt            time.Time `json:"updated_at"`
	EncryptionKeyVersion int64     `json:"encryption_key_version"`
	DataFormatVersion    int64     `json:"data_format_version"`
	MutationVersion      int64     `json:"mutation_version"`
}

type BudgetSpaceInvite struct {
	ID              string         `json:"id"`
	SpaceID         string         `json:"space_id"`
	InviterUserID   string         `json:"inviter_user_id"`
	InviteeEmail    sql.NullString `json:"invitee_email"`
	InviteSecret    string         `json:"invite_secret"`
	EncryptedBundle sql.NullString `json:"encrypted_bundle"`
	Status          string         `json:"status"`
	ExpiresAt       sql.NullTime   `json:"expires_at"`
	RedeemedAt      sql.NullTime   `json:"redeemed_at"`
	RedeemedBy      sql.NullString `json:"redeemed_by"`
	CreatedAt       time.Time      `json:"created_at"`
}

type BudgetSpaceMember struct {
	ID                int64          `json:"id"`
	SpaceID           string         `json:"space_id"`
	UserID            string         `json:"user_id"`
	Role              string         `json:"role"`
	EncryptedSpaceKey string         `json:"encrypted_space_key"`
	InvitationStatus  string         `json:"invitation_status"`
	InviteSecret      sql.NullString `json:"invite_secret"`
	InvitedAt         time.Time      `json:"invited_at"`
	AcceptedAt        sql.NullTime   `json:"accepted_at"`
}

type ExchangeRate struct {
	BaseCurrency   string    `json:"base_currency"`
	TargetCurrency string    `json:"target_currency"`
	Month          string    `json:"month"`
	Rate           float64   `json:"rate"`
	UpdatedAt      time.Time `json:"updated_at"`
}

type LocalCredential struct {
	UserID       string       `json:"user_id"`
	PasswordHash string       `json:"password_hash"`
	IsAdmin      bool         `json:"is_admin"`
	LastLoginAt  sql.NullTime `json:"last_login_at"`
	CreatedAt    time.Time    `json:"created_at"`
	UpdatedAt    sql.NullTime `json:"updated_at"`
}

type MutationLog struct {
	ID               string         `json:"id"`
	SpaceID          string         `json:"space_id"`
	UserID           string         `json:"user_id"`
	Version          int64          `json:"version"`
	Op               sql.NullString `json:"op"`
	Args             sql.NullString `json:"args"`
	EncryptedPayload sql.NullString `json:"encrypted_payload"`
	Timestamp        time.Time      `json:"timestamp"`
	BaseVersion      int64          `json:"base_version"`
	CreatedAt        sql.NullTime   `json:"created_at"`
}

type MutationSnapshot struct {
	SpaceID   string       `json:"space_id"`
	Version   int64        `json:"version"`
	Data      []byte       `json:"data"`
	Hash      string       `json:"hash"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type PushApiToken struct {
	UserID    string       `json:"user_id"`
	TokenHash string       `json:"token_hash"`
	SpaceID   string       `json:"space_id"`
	CreatedAt time.Time    `json:"created_at"`
	LastUsed  sql.NullTime `json:"last_used"`
	IsEnabled bool         `json:"is_enabled"`
}

type PushQueue struct {
	ID               string         `json:"id"`
	UserID           string         `json:"user_id"`
	SpaceID          string         `json:"space_id"`
	MessageID        sql.NullString `json:"message_id"`
	EncryptedPayload string         `json:"encrypted_payload"`
	Status           string         `json:"status"`
	CreatedAt        time.Time      `json:"created_at"`
	ProcessedAt      sql.NullTime   `json:"processed_at"`
}

type SavedQuery struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	Query     string    `json:"query"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type SentEmail struct {
	UserID   string    `json:"user_id"`
	Template string    `json:"template"`
	SentAt   time.Time `json:"sent_at"`
}

type TrialDiscountCode struct {
	Code          string         `json:"code"`
	UserID        string         `json:"user_id"`
	Tier          int64          `json:"tier"`
	PercentOff    int64          `json:"percent_off"`
	LsDiscountID  string         `json:"ls_discount_id"`
	GeneratedAt   time.Time      `json:"generated_at"`
	ValidFrom     time.Time      `json:"valid_from"`
	ValidUntil    time.Time      `json:"valid_until"`
	RedeemedAt    sql.NullTime   `json:"redeemed_at"`
	RedeemedSubID sql.NullString `json:"redeemed_sub_id"`
}

type TrialProgress struct {
	UserID                   string       `json:"user_id"`
	TrialStartedAt           time.Time    `json:"trial_started_at"`
	DailyLoggingDistinctDays int64        `json:"daily_logging_distinct_days"`
	ReconciliationCount      int64        `json:"reconciliation_count"`
	FirstReconciliationAt    sql.NullTime `json:"first_reconciliation_at"`
	SecondReconciliationAt   sql.NullTime `json:"second_reconciliation_at"`
	BudgetCycleAssignedAt    sql.NullTime `json:"budget_cycle_assigned_at"`
	OverspendCoveredAt       sql.NullTime `json:"overspend_covered_at"`
	GoalFundedAt             sql.NullTime `json:"goal_funded_at"`
	RuleAppliedHistoricalAt  sql.NullTime `json:"rule_applied_historical_at"`
	MonthlyReviewAt          sql.NullTime `json:"monthly_review_at"`
	Tier1UnlockedAt          sql.NullTime `json:"tier1_unlocked_at"`
	Tier2UnlockedAt          sql.NullTime `json:"tier2_unlocked_at"`
	Tier3UnlockedAt          sql.NullTime `json:"tier3_unlocked_at"`
	UpdatedAt                time.Time    `json:"updated_at"`
}

type TrialSignal struct {
	UserID  string    `json:"user_id"`
	Kind    string    `json:"kind"`
	Day     string    `json:"day"`
	Count   int64     `json:"count"`
	FirstAt time.Time `json:"first_at"`
	LastAt  time.Time `json:"last_at"`
}

type User struct {
	ID                          string         `json:"id"`
	Name                        string         `json:"name"`
	Email                       string         `json:"email"`
	DbPath                      string         `json:"db_path"`
	IsMasterPasswordSet         bool           `json:"is_master_password_set"`
	CurrentDbHash               string         `json:"current_db_hash"`
	SyncVersion                 int64          `json:"sync_version"`
	CreatedAt                   sql.NullTime   `json:"created_at"`
	LastUserDbBackup            sql.NullTime   `json:"last_user_db_backup"`
	BackupReminderFrequencyDays int64          `json:"backup_reminder_frequency_days"`
	IsBlocked                   bool           `json:"is_blocked"`
	SubscriptionStatus          sql.NullString `json:"subscription_status"`
	SubscriptionID              sql.NullString `json:"subscription_id"`
	CustomerID                  sql.NullString `json:"customer_id"`
	VariantID                   sql.NullString `json:"variant_id"`
	SubscriptionEndsAt          sql.NullTime   `json:"subscription_ends_at"`
	TrialEndsAt                 sql.NullTime   `json:"trial_ends_at"`
	CurrentPeriodEnd            sql.NullTime   `json:"current_period_end"`
	HasBetaAccess               bool           `json:"has_beta_access"`
	BetaExpiresAt               sql.NullTime   `json:"beta_expires_at"`
	IsFoundingMember            bool           `json:"is_founding_member"`
	HasCollaborationAccess      bool           `json:"has_collaboration_access"`
	OnboardingStatus            string         `json:"onboarding_status"`
	OnboardingCompletedAt       sql.NullTime   `json:"onboarding_completed_at"`
	OnboardingSnoozedUntil      sql.NullTime   `json:"onboarding_snoozed_until"`
	PrimarySpaceID              sql.NullString `json:"primary_space_id"`
	IsAnalyticsDisabled         bool           `json:"is_analytics_disabled"`
	SubscribedAt                sql.NullTime   `json:"subscribed_at"`
	WhereHeardAbout             string         `json:"where_heard_about"`
	IsTrialSignalsDisabled      bool           `json:"is_trial_signals_disabled"`
}

type UserDailyActivity struct {
	UserID      string    `json:"user_id"`
	Day         string    `json:"day"`
	FirstSeenAt time.Time `json:"first_seen_at"`
	LastSeenAt  time.Time `json:"last_seen_at"`
	HitCount    int64     `json:"hit_count"`
}

type UserFeedback struct {
	ID          string    `json:"id"`
	UserID      string    `json:"user_id"`
	Category    string    `json:"category"`
	Body        string    `json:"body"`
	ContactBack bool      `json:"contact_back"`
	ScreenPath  string    `json:"screen_path"`
	AppVersion  string    `json:"app_version"`
	UserAgent   string    `json:"user_agent"`
	CreatedAt   time.Time `json:"created_at"`
}

type UserPreference struct {
	UserID                    string    `json:"user_id"`
	ThemeMode                 string    `json:"theme_mode"`
	ThemePreset               string    `json:"theme_preset"`
	ClassicFont               string    `json:"classic_font"`
	HomePage                  string    `json:"home_page"`
	DesktopBudgetLayout       string    `json:"desktop_budget_layout"`
	CompactMobileLayout       bool      `json:"compact_mobile_layout"`
	MobileBudgetLayout        string    `json:"mobile_budget_layout"`
	CreatedAt                 time.Time `json:"created_at"`
	UpdatedAt                 time.Time `json:"updated_at"`
	MasterPasswordStorageMode string    `json:"master_password_storage_mode"`
	MasterPasswordStorageDays int64     `json:"master_password_storage_days"`
}
