// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mutations.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const countUserMutations = `-- name: CountUserMutations :one
SELECT COUNT(*) FROM mutation_log WHERE user_id = ?
`

func (q *Queries) CountUserMutations(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUserMutations, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMutation = `-- name: CreateMutation :exec
INSERT INTO mutation_log (
    id, space_id, user_id, version, op, args,
    encrypted_payload, timestamp, base_version, created_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, datetime('now'))
`

type CreateMutationParams struct {
	ID               string         `json:"id"`
	SpaceID          string         `json:"space_id"`
	UserID           string         `json:"user_id"`
	Version          int64          `json:"version"`
	Op               sql.NullString `json:"op"`
	Args             sql.NullString `json:"args"`
	EncryptedPayload sql.NullString `json:"encrypted_payload"`
	Timestamp        time.Time      `json:"timestamp"`
	BaseVersion      int64          `json:"base_version"`
}

func (q *Queries) CreateMutation(ctx context.Context, arg CreateMutationParams) error {
	_, err := q.db.ExecContext(ctx, createMutation,
		arg.ID,
		arg.SpaceID,
		arg.UserID,
		arg.Version,
		arg.Op,
		arg.Args,
		arg.EncryptedPayload,
		arg.Timestamp,
		arg.BaseVersion,
	)
	return err
}

const getLastUserMutation = `-- name: GetLastUserMutation :one
SELECT id, space_id, user_id, version, op, args, encrypted_payload, timestamp, base_version, created_at
FROM mutation_log
WHERE user_id = ?
ORDER BY timestamp DESC, version DESC
LIMIT 1
`

func (q *Queries) GetLastUserMutation(ctx context.Context, userID string) (MutationLog, error) {
	row := q.db.QueryRowContext(ctx, getLastUserMutation, userID)
	var i MutationLog
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.UserID,
		&i.Version,
		&i.Op,
		&i.Args,
		&i.EncryptedPayload,
		&i.Timestamp,
		&i.BaseVersion,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestMutationVersion = `-- name: GetLatestMutationVersion :one
SELECT COALESCE(MAX(version), 0) AS version
FROM mutation_log
WHERE space_id = ?
`

func (q *Queries) GetLatestMutationVersion(ctx context.Context, spaceID string) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getLatestMutationVersion, spaceID)
	var version interface{}
	err := row.Scan(&version)
	return version, err
}

const listUserMutationDays = `-- name: ListUserMutationDays :many
SELECT
    substr(timestamp, 1, 10) AS day,
    COUNT(*) AS count
FROM mutation_log
WHERE user_id = ?
  AND substr(timestamp, 1, 10) >= ?
  AND substr(timestamp, 1, 10) < ?
GROUP BY substr(timestamp, 1, 10)
ORDER BY day ASC
`

type ListUserMutationDaysParams struct {
	UserID      string    `json:"user_id"`
	Timestamp   time.Time `json:"timestamp"`
	Timestamp_2 time.Time `json:"timestamp_2"`
}

type ListUserMutationDaysRow struct {
	Day   string `json:"day"`
	Count int64  `json:"count"`
}

func (q *Queries) ListUserMutationDays(ctx context.Context, arg ListUserMutationDaysParams) ([]ListUserMutationDaysRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserMutationDays, arg.UserID, arg.Timestamp, arg.Timestamp_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserMutationDaysRow{}
	for rows.Next() {
		var i ListUserMutationDaysRow
		if err := rows.Scan(&i.Day, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
