// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: push.sql

package sqlc

import (
	"context"
	"database/sql"
)

const checkDuplicateMessageID = `-- name: CheckDuplicateMessageID :one
SELECT id, status FROM push_queue
WHERE space_id = ? AND message_id = ?
LIMIT 1
`

type CheckDuplicateMessageIDParams struct {
	SpaceID   string         `json:"space_id"`
	MessageID sql.NullString `json:"message_id"`
}

type CheckDuplicateMessageIDRow struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) CheckDuplicateMessageID(ctx context.Context, arg CheckDuplicateMessageIDParams) (CheckDuplicateMessageIDRow, error) {
	row := q.db.QueryRowContext(ctx, checkDuplicateMessageID, arg.SpaceID, arg.MessageID)
	var i CheckDuplicateMessageIDRow
	err := row.Scan(&i.ID, &i.Status)
	return i, err
}

const clearAllPushQueue = `-- name: ClearAllPushQueue :execresult
DELETE FROM push_queue
WHERE user_id = ?
`

func (q *Queries) ClearAllPushQueue(ctx context.Context, userID string) (sql.Result, error) {
	return q.db.ExecContext(ctx, clearAllPushQueue, userID)
}

const clearPendingPushQueue = `-- name: ClearPendingPushQueue :execresult
DELETE FROM push_queue
WHERE user_id = ? AND status = 'pending'
`

func (q *Queries) ClearPendingPushQueue(ctx context.Context, userID string) (sql.Result, error) {
	return q.db.ExecContext(ctx, clearPendingPushQueue, userID)
}

const createPushAPIToken = `-- name: CreatePushAPIToken :exec
INSERT INTO push_api_tokens (user_id, token_hash, space_id, created_at, is_enabled)
VALUES (?, ?, ?, datetime('now'), 1)
`

type CreatePushAPITokenParams struct {
	UserID    string `json:"user_id"`
	TokenHash string `json:"token_hash"`
	SpaceID   string `json:"space_id"`
}

func (q *Queries) CreatePushAPIToken(ctx context.Context, arg CreatePushAPITokenParams) error {
	_, err := q.db.ExecContext(ctx, createPushAPIToken, arg.UserID, arg.TokenHash, arg.SpaceID)
	return err
}

const createPushQueueItem = `-- name: CreatePushQueueItem :exec
INSERT INTO push_queue (
    id, user_id, space_id, message_id, encrypted_payload, status, created_at
) VALUES (?, ?, ?, ?, ?, 'pending', datetime('now'))
`

type CreatePushQueueItemParams struct {
	ID               string         `json:"id"`
	UserID           string         `json:"user_id"`
	SpaceID          string         `json:"space_id"`
	MessageID        sql.NullString `json:"message_id"`
	EncryptedPayload string         `json:"encrypted_payload"`
}

func (q *Queries) CreatePushQueueItem(ctx context.Context, arg CreatePushQueueItemParams) error {
	_, err := q.db.ExecContext(ctx, createPushQueueItem,
		arg.ID,
		arg.UserID,
		arg.SpaceID,
		arg.MessageID,
		arg.EncryptedPayload,
	)
	return err
}

const deleteProcessedPushItems = `-- name: DeleteProcessedPushItems :exec
DELETE FROM push_queue
WHERE status = 'processed' AND processed_at < ?
`

func (q *Queries) DeleteProcessedPushItems(ctx context.Context, processedAt sql.NullTime) error {
	_, err := q.db.ExecContext(ctx, deleteProcessedPushItems, processedAt)
	return err
}

const deletePushAPIToken = `-- name: DeletePushAPIToken :exec
DELETE FROM push_api_tokens WHERE user_id = ?
`

func (q *Queries) DeletePushAPIToken(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deletePushAPIToken, userID)
	return err
}

const deletePushQueueItem = `-- name: DeletePushQueueItem :exec
DELETE FROM push_queue WHERE id = ?
`

func (q *Queries) DeletePushQueueItem(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deletePushQueueItem, id)
	return err
}

const disablePushToken = `-- name: DisablePushToken :exec
UPDATE push_api_tokens SET is_enabled = 0 WHERE user_id = ?
`

func (q *Queries) DisablePushToken(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, disablePushToken, userID)
	return err
}

const getPushAPIToken = `-- name: GetPushAPIToken :one
SELECT user_id, token_hash, space_id, created_at, last_used, is_enabled FROM push_api_tokens WHERE user_id = ?
`

func (q *Queries) GetPushAPIToken(ctx context.Context, userID string) (PushApiToken, error) {
	row := q.db.QueryRowContext(ctx, getPushAPIToken, userID)
	var i PushApiToken
	err := row.Scan(
		&i.UserID,
		&i.TokenHash,
		&i.SpaceID,
		&i.CreatedAt,
		&i.LastUsed,
		&i.IsEnabled,
	)
	return i, err
}

const getPushAPITokenByHash = `-- name: GetPushAPITokenByHash :one
SELECT user_id, token_hash, space_id, created_at, last_used, is_enabled FROM push_api_tokens WHERE token_hash = ?
`

func (q *Queries) GetPushAPITokenByHash(ctx context.Context, tokenHash string) (PushApiToken, error) {
	row := q.db.QueryRowContext(ctx, getPushAPITokenByHash, tokenHash)
	var i PushApiToken
	err := row.Scan(
		&i.UserID,
		&i.TokenHash,
		&i.SpaceID,
		&i.CreatedAt,
		&i.LastUsed,
		&i.IsEnabled,
	)
	return i, err
}

const getPushQueueItem = `-- name: GetPushQueueItem :one
SELECT id, user_id, space_id, message_id, encrypted_payload, status, created_at, processed_at FROM push_queue WHERE id = ?
`

func (q *Queries) GetPushQueueItem(ctx context.Context, id string) (PushQueue, error) {
	row := q.db.QueryRowContext(ctx, getPushQueueItem, id)
	var i PushQueue
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SpaceID,
		&i.MessageID,
		&i.EncryptedPayload,
		&i.Status,
		&i.CreatedAt,
		&i.ProcessedAt,
	)
	return i, err
}

const getPushQueueStats = `-- name: GetPushQueueStats :one
SELECT
    COALESCE(SUM(CASE WHEN status = 'pending' THEN 1 ELSE 0 END), 0) AS pending_count,
    COALESCE(SUM(CASE WHEN status = 'processed' THEN 1 ELSE 0 END), 0) AS processed_count,
    COALESCE(SUM(CASE WHEN status = 'failed' THEN 1 ELSE 0 END), 0) AS failed_count
FROM push_queue
WHERE user_id = ?
`

type GetPushQueueStatsRow struct {
	PendingCount   interface{} `json:"pending_count"`
	ProcessedCount interface{} `json:"processed_count"`
	FailedCount    interface{} `json:"failed_count"`
}

func (q *Queries) GetPushQueueStats(ctx context.Context, userID string) (GetPushQueueStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getPushQueueStats, userID)
	var i GetPushQueueStatsRow
	err := row.Scan(&i.PendingCount, &i.ProcessedCount, &i.FailedCount)
	return i, err
}

const listPendingPushItems = `-- name: ListPendingPushItems :many
SELECT id, user_id, space_id, message_id, encrypted_payload, status, created_at, processed_at FROM push_queue
WHERE space_id = ? AND status = 'pending'
ORDER BY created_at ASC
`

func (q *Queries) ListPendingPushItems(ctx context.Context, spaceID string) ([]PushQueue, error) {
	rows, err := q.db.QueryContext(ctx, listPendingPushItems, spaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PushQueue{}
	for rows.Next() {
		var i PushQueue
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SpaceID,
			&i.MessageID,
			&i.EncryptedPayload,
			&i.Status,
			&i.CreatedAt,
			&i.ProcessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingPushItemsForUser = `-- name: ListPendingPushItemsForUser :many
SELECT id, user_id, space_id, message_id, encrypted_payload, status, created_at, processed_at FROM push_queue
WHERE user_id = ? AND status = 'pending'
ORDER BY created_at ASC
LIMIT 100
`

func (q *Queries) ListPendingPushItemsForUser(ctx context.Context, userID string) ([]PushQueue, error) {
	rows, err := q.db.QueryContext(ctx, listPendingPushItemsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PushQueue{}
	for rows.Next() {
		var i PushQueue
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SpaceID,
			&i.MessageID,
			&i.EncryptedPayload,
			&i.Status,
			&i.CreatedAt,
			&i.ProcessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingPushItemsForUserAndSpace = `-- name: ListPendingPushItemsForUserAndSpace :many
SELECT id, user_id, space_id, message_id, encrypted_payload, status, created_at, processed_at FROM push_queue
WHERE user_id = ? AND space_id = ? AND status = 'pending'
ORDER BY created_at ASC
LIMIT 100
`

type ListPendingPushItemsForUserAndSpaceParams struct {
	UserID  string `json:"user_id"`
	SpaceID string `json:"space_id"`
}

func (q *Queries) ListPendingPushItemsForUserAndSpace(ctx context.Context, arg ListPendingPushItemsForUserAndSpaceParams) ([]PushQueue, error) {
	rows, err := q.db.QueryContext(ctx, listPendingPushItemsForUserAndSpace, arg.UserID, arg.SpaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PushQueue{}
	for rows.Next() {
		var i PushQueue
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SpaceID,
			&i.MessageID,
			&i.EncryptedPayload,
			&i.Status,
			&i.CreatedAt,
			&i.ProcessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPushProcessed = `-- name: MarkPushProcessed :exec
UPDATE push_queue
SET status = 'processed', processed_at = datetime('now')
WHERE id = ?
`

func (q *Queries) MarkPushProcessed(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, markPushProcessed, id)
	return err
}

const markPushTokenUsed = `-- name: MarkPushTokenUsed :exec
UPDATE push_api_tokens
SET last_used = datetime('now')
WHERE user_id = ?
`

func (q *Queries) MarkPushTokenUsed(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, markPushTokenUsed, userID)
	return err
}

const setPushTokenEnabled = `-- name: SetPushTokenEnabled :exec
UPDATE push_api_tokens SET is_enabled = ? WHERE user_id = ?
`

type SetPushTokenEnabledParams struct {
	IsEnabled bool   `json:"is_enabled"`
	UserID    string `json:"user_id"`
}

func (q *Queries) SetPushTokenEnabled(ctx context.Context, arg SetPushTokenEnabledParams) error {
	_, err := q.db.ExecContext(ctx, setPushTokenEnabled, arg.IsEnabled, arg.UserID)
	return err
}

const updatePushAPIToken = `-- name: UpdatePushAPIToken :exec
UPDATE push_api_tokens
SET token_hash = ?, space_id = ?, last_used = NULL, is_enabled = 1
WHERE user_id = ?
`

type UpdatePushAPITokenParams struct {
	TokenHash string `json:"token_hash"`
	SpaceID   string `json:"space_id"`
	UserID    string `json:"user_id"`
}

func (q *Queries) UpdatePushAPIToken(ctx context.Context, arg UpdatePushAPITokenParams) error {
	_, err := q.db.ExecContext(ctx, updatePushAPIToken, arg.TokenHash, arg.SpaceID, arg.UserID)
	return err
}

const updatePushQueueItemStatus = `-- name: UpdatePushQueueItemStatus :exec
UPDATE push_queue
SET status = ?, processed_at = datetime('now')
WHERE id = ? AND user_id = ?
`

type UpdatePushQueueItemStatusParams struct {
	Status string `json:"status"`
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) UpdatePushQueueItemStatus(ctx context.Context, arg UpdatePushQueueItemStatusParams) error {
	_, err := q.db.ExecContext(ctx, updatePushQueueItemStatus, arg.Status, arg.ID, arg.UserID)
	return err
}

const upsertPushAPIToken = `-- name: UpsertPushAPIToken :exec
INSERT INTO push_api_tokens (user_id, token_hash, space_id, created_at, is_enabled)
VALUES (?, ?, ?, datetime('now'), 1)
ON CONFLICT(user_id) DO UPDATE SET
    token_hash = excluded.token_hash,
    space_id = excluded.space_id,
    created_at = excluded.created_at,
    is_enabled = 1,
    last_used = NULL
`

type UpsertPushAPITokenParams struct {
	UserID    string `json:"user_id"`
	TokenHash string `json:"token_hash"`
	SpaceID   string `json:"space_id"`
}

func (q *Queries) UpsertPushAPIToken(ctx context.Context, arg UpsertPushAPITokenParams) error {
	_, err := q.db.ExecContext(ctx, upsertPushAPIToken, arg.UserID, arg.TokenHash, arg.SpaceID)
	return err
}
