// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rewards_analytics.sql

package sqlc

import (
	"context"
	"database/sql"
)

const analyticsFunnelByCohort = `-- name: AnalyticsFunnelByCohort :many
SELECT
    strftime(?, substr(u.created_at, 1, 19)) AS cohort,
    CAST(COUNT(*) AS INTEGER) AS signups,
    CAST(SUM(CASE WHEN tp.tier1_unlocked_at IS NOT NULL THEN 1 ELSE 0 END) AS INTEGER) AS tier1,
    CAST(SUM(CASE WHEN tp.tier2_unlocked_at IS NOT NULL THEN 1 ELSE 0 END) AS INTEGER) AS tier2,
    CAST(SUM(CASE WHEN tp.tier3_unlocked_at IS NOT NULL THEN 1 ELSE 0 END) AS INTEGER) AS tier3,
    CAST(SUM(CASE WHEN u.subscribed_at IS NOT NULL THEN 1 ELSE 0 END) AS INTEGER) AS subscribed
FROM users u
LEFT JOIN trial_progress tp ON tp.user_id = u.id
WHERE u.created_at >= ?
  AND u.created_at < ?
  AND u.email NOT LIKE '%@clerk.user'
GROUP BY cohort
ORDER BY cohort
`

type AnalyticsFunnelByCohortParams struct {
	Strftime    interface{}  `json:"strftime"`
	CreatedAt   sql.NullTime `json:"created_at"`
	CreatedAt_2 sql.NullTime `json:"created_at_2"`
}

type AnalyticsFunnelByCohortRow struct {
	Cohort     interface{} `json:"cohort"`
	Signups    int64       `json:"signups"`
	Tier1      int64       `json:"tier1"`
	Tier2      int64       `json:"tier2"`
	Tier3      int64       `json:"tier3"`
	Subscribed int64       `json:"subscribed"`
}

// Cohort = signup period. Counts how many users from each signup cohort
// reached each subsequent funnel stage at any later time.
func (q *Queries) AnalyticsFunnelByCohort(ctx context.Context, arg AnalyticsFunnelByCohortParams) ([]AnalyticsFunnelByCohortRow, error) {
	rows, err := q.db.QueryContext(ctx, analyticsFunnelByCohort, arg.Strftime, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AnalyticsFunnelByCohortRow{}
	for rows.Next() {
		var i AnalyticsFunnelByCohortRow
		if err := rows.Scan(
			&i.Cohort,
			&i.Signups,
			&i.Tier1,
			&i.Tier2,
			&i.Tier3,
			&i.Subscribed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const analyticsRedemptionsByPeriod = `-- name: AnalyticsRedemptionsByPeriod :many
SELECT strftime(?, substr(redeemed_at, 1, 19)) AS period, COUNT(*) AS count
FROM trial_discount_codes
WHERE redeemed_at IS NOT NULL
  AND redeemed_at >= ?
  AND redeemed_at < ?
GROUP BY period
ORDER BY period
`

type AnalyticsRedemptionsByPeriodParams struct {
	Strftime     interface{}  `json:"strftime"`
	RedeemedAt   sql.NullTime `json:"redeemed_at"`
	RedeemedAt_2 sql.NullTime `json:"redeemed_at_2"`
}

type AnalyticsRedemptionsByPeriodRow struct {
	Period interface{} `json:"period"`
	Count  int64       `json:"count"`
}

func (q *Queries) AnalyticsRedemptionsByPeriod(ctx context.Context, arg AnalyticsRedemptionsByPeriodParams) ([]AnalyticsRedemptionsByPeriodRow, error) {
	rows, err := q.db.QueryContext(ctx, analyticsRedemptionsByPeriod, arg.Strftime, arg.RedeemedAt, arg.RedeemedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AnalyticsRedemptionsByPeriodRow{}
	for rows.Next() {
		var i AnalyticsRedemptionsByPeriodRow
		if err := rows.Scan(&i.Period, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const analyticsSignupsByPeriod = `-- name: AnalyticsSignupsByPeriod :many

SELECT strftime(?, substr(created_at, 1, 19)) AS period, COUNT(*) AS count
FROM users
WHERE created_at IS NOT NULL
  AND created_at >= ?
  AND created_at < ?
  AND email NOT LIKE '%@clerk.user'
GROUP BY period
ORDER BY period
`

type AnalyticsSignupsByPeriodParams struct {
	Strftime    interface{}  `json:"strftime"`
	CreatedAt   sql.NullTime `json:"created_at"`
	CreatedAt_2 sql.NullTime `json:"created_at_2"`
}

type AnalyticsSignupsByPeriodRow struct {
	Period interface{} `json:"period"`
	Count  int64       `json:"count"`
}

// The substr(col, 1, 19) calls below trim Go's t.String() output
// ("2026-04-01 22:37:12.999 +0200 CEST m=+...") down to "2026-04-01 22:37:12"
// which strftime can actually parse. Without this, modernc.org/sqlite's
// t.String() bind format makes strftime return NULL for every row, collapsing
// the chart to a single NULL bucket. Safe for RFC3339-style values too.
func (q *Queries) AnalyticsSignupsByPeriod(ctx context.Context, arg AnalyticsSignupsByPeriodParams) ([]AnalyticsSignupsByPeriodRow, error) {
	rows, err := q.db.QueryContext(ctx, analyticsSignupsByPeriod, arg.Strftime, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AnalyticsSignupsByPeriodRow{}
	for rows.Next() {
		var i AnalyticsSignupsByPeriodRow
		if err := rows.Scan(&i.Period, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const analyticsSubscriptionsByPeriod = `-- name: AnalyticsSubscriptionsByPeriod :many
SELECT strftime(?, substr(subscribed_at, 1, 19)) AS period, COUNT(*) AS count
FROM users
WHERE subscribed_at IS NOT NULL
  AND subscribed_at >= ?
  AND subscribed_at < ?
GROUP BY period
ORDER BY period
`

type AnalyticsSubscriptionsByPeriodParams struct {
	Strftime       interface{}  `json:"strftime"`
	SubscribedAt   sql.NullTime `json:"subscribed_at"`
	SubscribedAt_2 sql.NullTime `json:"subscribed_at_2"`
}

type AnalyticsSubscriptionsByPeriodRow struct {
	Period interface{} `json:"period"`
	Count  int64       `json:"count"`
}

func (q *Queries) AnalyticsSubscriptionsByPeriod(ctx context.Context, arg AnalyticsSubscriptionsByPeriodParams) ([]AnalyticsSubscriptionsByPeriodRow, error) {
	rows, err := q.db.QueryContext(ctx, analyticsSubscriptionsByPeriod, arg.Strftime, arg.SubscribedAt, arg.SubscribedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AnalyticsSubscriptionsByPeriodRow{}
	for rows.Next() {
		var i AnalyticsSubscriptionsByPeriodRow
		if err := rows.Scan(&i.Period, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const analyticsTier1UnlocksByPeriod = `-- name: AnalyticsTier1UnlocksByPeriod :many
SELECT strftime(?, substr(tier1_unlocked_at, 1, 19)) AS period, COUNT(*) AS count
FROM trial_progress
WHERE tier1_unlocked_at IS NOT NULL
  AND tier1_unlocked_at >= ?
  AND tier1_unlocked_at < ?
GROUP BY period
ORDER BY period
`

type AnalyticsTier1UnlocksByPeriodParams struct {
	Strftime          interface{}  `json:"strftime"`
	Tier1UnlockedAt   sql.NullTime `json:"tier1_unlocked_at"`
	Tier1UnlockedAt_2 sql.NullTime `json:"tier1_unlocked_at_2"`
}

type AnalyticsTier1UnlocksByPeriodRow struct {
	Period interface{} `json:"period"`
	Count  int64       `json:"count"`
}

func (q *Queries) AnalyticsTier1UnlocksByPeriod(ctx context.Context, arg AnalyticsTier1UnlocksByPeriodParams) ([]AnalyticsTier1UnlocksByPeriodRow, error) {
	rows, err := q.db.QueryContext(ctx, analyticsTier1UnlocksByPeriod, arg.Strftime, arg.Tier1UnlockedAt, arg.Tier1UnlockedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AnalyticsTier1UnlocksByPeriodRow{}
	for rows.Next() {
		var i AnalyticsTier1UnlocksByPeriodRow
		if err := rows.Scan(&i.Period, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const analyticsTier2UnlocksByPeriod = `-- name: AnalyticsTier2UnlocksByPeriod :many
SELECT strftime(?, substr(tier2_unlocked_at, 1, 19)) AS period, COUNT(*) AS count
FROM trial_progress
WHERE tier2_unlocked_at IS NOT NULL
  AND tier2_unlocked_at >= ?
  AND tier2_unlocked_at < ?
GROUP BY period
ORDER BY period
`

type AnalyticsTier2UnlocksByPeriodParams struct {
	Strftime          interface{}  `json:"strftime"`
	Tier2UnlockedAt   sql.NullTime `json:"tier2_unlocked_at"`
	Tier2UnlockedAt_2 sql.NullTime `json:"tier2_unlocked_at_2"`
}

type AnalyticsTier2UnlocksByPeriodRow struct {
	Period interface{} `json:"period"`
	Count  int64       `json:"count"`
}

func (q *Queries) AnalyticsTier2UnlocksByPeriod(ctx context.Context, arg AnalyticsTier2UnlocksByPeriodParams) ([]AnalyticsTier2UnlocksByPeriodRow, error) {
	rows, err := q.db.QueryContext(ctx, analyticsTier2UnlocksByPeriod, arg.Strftime, arg.Tier2UnlockedAt, arg.Tier2UnlockedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AnalyticsTier2UnlocksByPeriodRow{}
	for rows.Next() {
		var i AnalyticsTier2UnlocksByPeriodRow
		if err := rows.Scan(&i.Period, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const analyticsTier3UnlocksByPeriod = `-- name: AnalyticsTier3UnlocksByPeriod :many
SELECT strftime(?, substr(tier3_unlocked_at, 1, 19)) AS period, COUNT(*) AS count
FROM trial_progress
WHERE tier3_unlocked_at IS NOT NULL
  AND tier3_unlocked_at >= ?
  AND tier3_unlocked_at < ?
GROUP BY period
ORDER BY period
`

type AnalyticsTier3UnlocksByPeriodParams struct {
	Strftime          interface{}  `json:"strftime"`
	Tier3UnlockedAt   sql.NullTime `json:"tier3_unlocked_at"`
	Tier3UnlockedAt_2 sql.NullTime `json:"tier3_unlocked_at_2"`
}

type AnalyticsTier3UnlocksByPeriodRow struct {
	Period interface{} `json:"period"`
	Count  int64       `json:"count"`
}

func (q *Queries) AnalyticsTier3UnlocksByPeriod(ctx context.Context, arg AnalyticsTier3UnlocksByPeriodParams) ([]AnalyticsTier3UnlocksByPeriodRow, error) {
	rows, err := q.db.QueryContext(ctx, analyticsTier3UnlocksByPeriod, arg.Strftime, arg.Tier3UnlockedAt, arg.Tier3UnlockedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AnalyticsTier3UnlocksByPeriodRow{}
	for rows.Next() {
		var i AnalyticsTier3UnlocksByPeriodRow
		if err := rows.Scan(&i.Period, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
