// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: space_blobs.sql

package sqlc

import (
	"context"
	"time"
)

const createSpaceBlob = `-- name: CreateSpaceBlob :exec
INSERT INTO budget_space_blobs (space_id, blob_path, current_hash, sync_version, size_bytes, encryption_key_version, updated_at)
VALUES (?, ?, '', 0, 0, 1, ?)
`

type CreateSpaceBlobParams struct {
	SpaceID   string    `json:"space_id"`
	BlobPath  string    `json:"blob_path"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) CreateSpaceBlob(ctx context.Context, arg CreateSpaceBlobParams) error {
	_, err := q.db.ExecContext(ctx, createSpaceBlob, arg.SpaceID, arg.BlobPath, arg.UpdatedAt)
	return err
}

const deleteSpaceBlob = `-- name: DeleteSpaceBlob :exec
DELETE FROM budget_space_blobs WHERE space_id = ?
`

func (q *Queries) DeleteSpaceBlob(ctx context.Context, spaceID string) error {
	_, err := q.db.ExecContext(ctx, deleteSpaceBlob, spaceID)
	return err
}

const getSpaceBlob = `-- name: GetSpaceBlob :one
SELECT space_id, blob_path, current_hash, sync_version, size_bytes, updated_at, encryption_key_version, data_format_version, mutation_version FROM budget_space_blobs WHERE space_id = ?
`

func (q *Queries) GetSpaceBlob(ctx context.Context, spaceID string) (BudgetSpaceBlob, error) {
	row := q.db.QueryRowContext(ctx, getSpaceBlob, spaceID)
	var i BudgetSpaceBlob
	err := row.Scan(
		&i.SpaceID,
		&i.BlobPath,
		&i.CurrentHash,
		&i.SyncVersion,
		&i.SizeBytes,
		&i.UpdatedAt,
		&i.EncryptionKeyVersion,
		&i.DataFormatVersion,
		&i.MutationVersion,
	)
	return i, err
}

const incrementEncryptionKeyVersion = `-- name: IncrementEncryptionKeyVersion :one
UPDATE budget_space_blobs
SET encryption_key_version = encryption_key_version + 1,
    updated_at = datetime('now')
WHERE space_id = ?
RETURNING encryption_key_version
`

func (q *Queries) IncrementEncryptionKeyVersion(ctx context.Context, spaceID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, incrementEncryptionKeyVersion, spaceID)
	var encryption_key_version int64
	err := row.Scan(&encryption_key_version)
	return encryption_key_version, err
}

const listSpaceBlobsByOwner = `-- name: ListSpaceBlobsByOwner :many
SELECT b.space_id, b.blob_path
FROM budget_space_blobs b
INNER JOIN budget_spaces s ON s.space_id = b.space_id
WHERE s.owner_user_id = ?
`

type ListSpaceBlobsByOwnerRow struct {
	SpaceID  string `json:"space_id"`
	BlobPath string `json:"blob_path"`
}

func (q *Queries) ListSpaceBlobsByOwner(ctx context.Context, ownerUserID string) ([]ListSpaceBlobsByOwnerRow, error) {
	rows, err := q.db.QueryContext(ctx, listSpaceBlobsByOwner, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSpaceBlobsByOwnerRow{}
	for rows.Next() {
		var i ListSpaceBlobsByOwnerRow
		if err := rows.Scan(&i.SpaceID, &i.BlobPath); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const raiseSpaceDataFormatVersion = `-- name: RaiseSpaceDataFormatVersion :exec
UPDATE budget_space_blobs
SET data_format_version = MAX(data_format_version, ?),
    updated_at = datetime('now')
WHERE space_id = ?
`

type RaiseSpaceDataFormatVersionParams struct {
	MAX     interface{} `json:"MAX"`
	SpaceID string      `json:"space_id"`
}

func (q *Queries) RaiseSpaceDataFormatVersion(ctx context.Context, arg RaiseSpaceDataFormatVersionParams) error {
	_, err := q.db.ExecContext(ctx, raiseSpaceDataFormatVersion, arg.MAX, arg.SpaceID)
	return err
}

const updateSpaceBlobMetadata = `-- name: UpdateSpaceBlobMetadata :exec
UPDATE budget_space_blobs
SET blob_path = ?, current_hash = ?, sync_version = ?, size_bytes = ?, updated_at = datetime('now')
WHERE space_id = ?
`

type UpdateSpaceBlobMetadataParams struct {
	BlobPath    string `json:"blob_path"`
	CurrentHash string `json:"current_hash"`
	SyncVersion int64  `json:"sync_version"`
	SizeBytes   int64  `json:"size_bytes"`
	SpaceID     string `json:"space_id"`
}

func (q *Queries) UpdateSpaceBlobMetadata(ctx context.Context, arg UpdateSpaceBlobMetadataParams) error {
	_, err := q.db.ExecContext(ctx, updateSpaceBlobMetadata,
		arg.BlobPath,
		arg.CurrentHash,
		arg.SyncVersion,
		arg.SizeBytes,
		arg.SpaceID,
	)
	return err
}

const updateSpaceSyncState = `-- name: UpdateSpaceSyncState :one
UPDATE budget_space_blobs
SET current_hash = ?,
    sync_version = sync_version + 1,
    size_bytes = ?,
    mutation_version = ?,
    updated_at = datetime('now')
WHERE space_id = ?
RETURNING sync_version
`

type UpdateSpaceSyncStateParams struct {
	CurrentHash     string `json:"current_hash"`
	SizeBytes       int64  `json:"size_bytes"`
	MutationVersion int64  `json:"mutation_version"`
	SpaceID         string `json:"space_id"`
}

func (q *Queries) UpdateSpaceSyncState(ctx context.Context, arg UpdateSpaceSyncStateParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, updateSpaceSyncState,
		arg.CurrentHash,
		arg.SizeBytes,
		arg.MutationVersion,
		arg.SpaceID,
	)
	var sync_version int64
	err := row.Scan(&sync_version)
	return sync_version, err
}

const updateSpaceSyncStateCAS = `-- name: UpdateSpaceSyncStateCAS :one
UPDATE budget_space_blobs
SET current_hash = ?,
    sync_version = sync_version + 1,
    size_bytes = ?,
    mutation_version = ?,
    updated_at = datetime('now')
WHERE space_id = ? AND sync_version = ?
RETURNING sync_version
`

type UpdateSpaceSyncStateCASParams struct {
	CurrentHash     string `json:"current_hash"`
	SizeBytes       int64  `json:"size_bytes"`
	MutationVersion int64  `json:"mutation_version"`
	SpaceID         string `json:"space_id"`
	SyncVersion     int64  `json:"sync_version"`
}

func (q *Queries) UpdateSpaceSyncStateCAS(ctx context.Context, arg UpdateSpaceSyncStateCASParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, updateSpaceSyncStateCAS,
		arg.CurrentHash,
		arg.SizeBytes,
		arg.MutationVersion,
		arg.SpaceID,
		arg.SyncVersion,
	)
	var sync_version int64
	err := row.Scan(&sync_version)
	return sync_version, err
}
