// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: space_invites.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createSpaceInvite = `-- name: CreateSpaceInvite :one
INSERT INTO budget_space_invites (
    id, space_id, inviter_user_id, invitee_email, invite_secret,
    encrypted_bundle, status, expires_at, created_at
) VALUES (?, ?, ?, ?, ?, '', 'pending', ?, ?)
RETURNING id, space_id, inviter_user_id, invitee_email, invite_secret, encrypted_bundle, status, expires_at, redeemed_at, redeemed_by, created_at
`

type CreateSpaceInviteParams struct {
	ID            string         `json:"id"`
	SpaceID       string         `json:"space_id"`
	InviterUserID string         `json:"inviter_user_id"`
	InviteeEmail  sql.NullString `json:"invitee_email"`
	InviteSecret  string         `json:"invite_secret"`
	ExpiresAt     sql.NullTime   `json:"expires_at"`
	CreatedAt     time.Time      `json:"created_at"`
}

func (q *Queries) CreateSpaceInvite(ctx context.Context, arg CreateSpaceInviteParams) (BudgetSpaceInvite, error) {
	row := q.db.QueryRowContext(ctx, createSpaceInvite,
		arg.ID,
		arg.SpaceID,
		arg.InviterUserID,
		arg.InviteeEmail,
		arg.InviteSecret,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	var i BudgetSpaceInvite
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.InviterUserID,
		&i.InviteeEmail,
		&i.InviteSecret,
		&i.EncryptedBundle,
		&i.Status,
		&i.ExpiresAt,
		&i.RedeemedAt,
		&i.RedeemedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAllInvitesForSpace = `-- name: DeleteAllInvitesForSpace :exec
DELETE FROM budget_space_invites WHERE space_id = ?
`

func (q *Queries) DeleteAllInvitesForSpace(ctx context.Context, spaceID string) error {
	_, err := q.db.ExecContext(ctx, deleteAllInvitesForSpace, spaceID)
	return err
}

const deleteSpaceInvite = `-- name: DeleteSpaceInvite :exec
DELETE FROM budget_space_invites WHERE id = ? AND space_id = ?
`

type DeleteSpaceInviteParams struct {
	ID      string `json:"id"`
	SpaceID string `json:"space_id"`
}

func (q *Queries) DeleteSpaceInvite(ctx context.Context, arg DeleteSpaceInviteParams) error {
	_, err := q.db.ExecContext(ctx, deleteSpaceInvite, arg.ID, arg.SpaceID)
	return err
}

const getSpaceInviteByID = `-- name: GetSpaceInviteByID :one
SELECT id, space_id, inviter_user_id, invitee_email, invite_secret, encrypted_bundle, status, expires_at, redeemed_at, redeemed_by, created_at FROM budget_space_invites WHERE id = ?
`

func (q *Queries) GetSpaceInviteByID(ctx context.Context, id string) (BudgetSpaceInvite, error) {
	row := q.db.QueryRowContext(ctx, getSpaceInviteByID, id)
	var i BudgetSpaceInvite
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.InviterUserID,
		&i.InviteeEmail,
		&i.InviteSecret,
		&i.EncryptedBundle,
		&i.Status,
		&i.ExpiresAt,
		&i.RedeemedAt,
		&i.RedeemedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getSpaceInviteBySecret = `-- name: GetSpaceInviteBySecret :one
SELECT
    i.id,
    i.space_id,
    s.display_name,
    i.inviter_user_id,
    i.encrypted_bundle,
    i.status,
    i.expires_at
FROM budget_space_invites i
INNER JOIN budget_spaces s ON s.space_id = i.space_id
WHERE i.invite_secret = ?
`

type GetSpaceInviteBySecretRow struct {
	ID              string         `json:"id"`
	SpaceID         string         `json:"space_id"`
	DisplayName     string         `json:"display_name"`
	InviterUserID   string         `json:"inviter_user_id"`
	EncryptedBundle sql.NullString `json:"encrypted_bundle"`
	Status          string         `json:"status"`
	ExpiresAt       sql.NullTime   `json:"expires_at"`
}

func (q *Queries) GetSpaceInviteBySecret(ctx context.Context, inviteSecret string) (GetSpaceInviteBySecretRow, error) {
	row := q.db.QueryRowContext(ctx, getSpaceInviteBySecret, inviteSecret)
	var i GetSpaceInviteBySecretRow
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.DisplayName,
		&i.InviterUserID,
		&i.EncryptedBundle,
		&i.Status,
		&i.ExpiresAt,
	)
	return i, err
}

const listSpaceInvites = `-- name: ListSpaceInvites :many
SELECT id, space_id, inviter_user_id, invitee_email, invite_secret, encrypted_bundle, status, expires_at, redeemed_at, redeemed_by, created_at FROM budget_space_invites
WHERE space_id = ?
ORDER BY created_at DESC
`

func (q *Queries) ListSpaceInvites(ctx context.Context, spaceID string) ([]BudgetSpaceInvite, error) {
	rows, err := q.db.QueryContext(ctx, listSpaceInvites, spaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BudgetSpaceInvite{}
	for rows.Next() {
		var i BudgetSpaceInvite
		if err := rows.Scan(
			&i.ID,
			&i.SpaceID,
			&i.InviterUserID,
			&i.InviteeEmail,
			&i.InviteSecret,
			&i.EncryptedBundle,
			&i.Status,
			&i.ExpiresAt,
			&i.RedeemedAt,
			&i.RedeemedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInviteExpired = `-- name: MarkInviteExpired :exec
UPDATE budget_space_invites
SET status = 'expired', invite_secret = ''
WHERE id = ?
`

func (q *Queries) MarkInviteExpired(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, markInviteExpired, id)
	return err
}

const markInviteRedeemed = `-- name: MarkInviteRedeemed :exec
UPDATE budget_space_invites
SET status = 'redeemed', redeemed_at = ?, redeemed_by = ?, invite_secret = ''
WHERE id = ?
`

type MarkInviteRedeemedParams struct {
	RedeemedAt sql.NullTime   `json:"redeemed_at"`
	RedeemedBy sql.NullString `json:"redeemed_by"`
	ID         string         `json:"id"`
}

func (q *Queries) MarkInviteRedeemed(ctx context.Context, arg MarkInviteRedeemedParams) error {
	_, err := q.db.ExecContext(ctx, markInviteRedeemed, arg.RedeemedAt, arg.RedeemedBy, arg.ID)
	return err
}

const updateInviteBundle = `-- name: UpdateInviteBundle :exec
UPDATE budget_space_invites
SET encrypted_bundle = ?
WHERE id = ? AND space_id = ? AND status = 'pending'
`

type UpdateInviteBundleParams struct {
	EncryptedBundle sql.NullString `json:"encrypted_bundle"`
	ID              string         `json:"id"`
	SpaceID         string         `json:"space_id"`
}

func (q *Queries) UpdateInviteBundle(ctx context.Context, arg UpdateInviteBundleParams) error {
	_, err := q.db.ExecContext(ctx, updateInviteBundle, arg.EncryptedBundle, arg.ID, arg.SpaceID)
	return err
}
