// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: space_members.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const countAcceptedMemberships = `-- name: CountAcceptedMemberships :one
SELECT COUNT(*) FROM budget_space_members
WHERE user_id = ? AND invitation_status = 'accepted'
`

func (q *Queries) CountAcceptedMemberships(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAcceptedMemberships, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSpaceMember = `-- name: CreateSpaceMember :exec
INSERT INTO budget_space_members (
    space_id, user_id, role, encrypted_space_key, invitation_status, invited_at, accepted_at
) VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateSpaceMemberParams struct {
	SpaceID           string       `json:"space_id"`
	UserID            string       `json:"user_id"`
	Role              string       `json:"role"`
	EncryptedSpaceKey string       `json:"encrypted_space_key"`
	InvitationStatus  string       `json:"invitation_status"`
	InvitedAt         time.Time    `json:"invited_at"`
	AcceptedAt        sql.NullTime `json:"accepted_at"`
}

func (q *Queries) CreateSpaceMember(ctx context.Context, arg CreateSpaceMemberParams) error {
	_, err := q.db.ExecContext(ctx, createSpaceMember,
		arg.SpaceID,
		arg.UserID,
		arg.Role,
		arg.EncryptedSpaceKey,
		arg.InvitationStatus,
		arg.InvitedAt,
		arg.AcceptedAt,
	)
	return err
}

const deleteAllMembershipsForSpace = `-- name: DeleteAllMembershipsForSpace :exec
DELETE FROM budget_space_members WHERE space_id = ?
`

func (q *Queries) DeleteAllMembershipsForSpace(ctx context.Context, spaceID string) error {
	_, err := q.db.ExecContext(ctx, deleteAllMembershipsForSpace, spaceID)
	return err
}

const deleteAllMembershipsForUser = `-- name: DeleteAllMembershipsForUser :exec
DELETE FROM budget_space_members WHERE user_id = ?
`

func (q *Queries) DeleteAllMembershipsForUser(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteAllMembershipsForUser, userID)
	return err
}

const deleteSpaceMember = `-- name: DeleteSpaceMember :exec
DELETE FROM budget_space_members WHERE space_id = ? AND user_id = ?
`

type DeleteSpaceMemberParams struct {
	SpaceID string `json:"space_id"`
	UserID  string `json:"user_id"`
}

func (q *Queries) DeleteSpaceMember(ctx context.Context, arg DeleteSpaceMemberParams) error {
	_, err := q.db.ExecContext(ctx, deleteSpaceMember, arg.SpaceID, arg.UserID)
	return err
}

const getFirstAcceptedMembership = `-- name: GetFirstAcceptedMembership :one
SELECT space_id
FROM budget_space_members
WHERE user_id = ? AND invitation_status = 'accepted'
ORDER BY CASE role WHEN 'owner' THEN 0 ELSE 1 END, invited_at
LIMIT 1
`

func (q *Queries) GetFirstAcceptedMembership(ctx context.Context, userID string) (string, error) {
	row := q.db.QueryRowContext(ctx, getFirstAcceptedMembership, userID)
	var space_id string
	err := row.Scan(&space_id)
	return space_id, err
}

const getMemberInvitationStatus = `-- name: GetMemberInvitationStatus :one
SELECT invitation_status FROM budget_space_members WHERE space_id = ? AND user_id = ?
`

type GetMemberInvitationStatusParams struct {
	SpaceID string `json:"space_id"`
	UserID  string `json:"user_id"`
}

func (q *Queries) GetMemberInvitationStatus(ctx context.Context, arg GetMemberInvitationStatusParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getMemberInvitationStatus, arg.SpaceID, arg.UserID)
	var invitation_status string
	err := row.Scan(&invitation_status)
	return invitation_status, err
}

const getSpaceMember = `-- name: GetSpaceMember :one
SELECT id, space_id, user_id, role, encrypted_space_key, invitation_status, invite_secret, invited_at, accepted_at FROM budget_space_members WHERE space_id = ? AND user_id = ?
`

type GetSpaceMemberParams struct {
	SpaceID string `json:"space_id"`
	UserID  string `json:"user_id"`
}

func (q *Queries) GetSpaceMember(ctx context.Context, arg GetSpaceMemberParams) (BudgetSpaceMember, error) {
	row := q.db.QueryRowContext(ctx, getSpaceMember, arg.SpaceID, arg.UserID)
	var i BudgetSpaceMember
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.UserID,
		&i.Role,
		&i.EncryptedSpaceKey,
		&i.InvitationStatus,
		&i.InviteSecret,
		&i.InvitedAt,
		&i.AcceptedAt,
	)
	return i, err
}

const listSpaceMembers = `-- name: ListSpaceMembers :many
SELECT
    m.space_id,
    m.user_id,
    COALESCE(u.name, '') AS user_name,
    COALESCE(u.email, '') AS user_email,
    m.role,
    m.encrypted_space_key,
    m.invitation_status,
    m.invite_secret,
    m.invited_at,
    m.accepted_at
FROM budget_space_members m
LEFT JOIN users u ON u.id = m.user_id
WHERE m.space_id = ?
ORDER BY m.role ASC, m.invited_at ASC
`

type ListSpaceMembersRow struct {
	SpaceID           string         `json:"space_id"`
	UserID            string         `json:"user_id"`
	UserName          string         `json:"user_name"`
	UserEmail         string         `json:"user_email"`
	Role              string         `json:"role"`
	EncryptedSpaceKey string         `json:"encrypted_space_key"`
	InvitationStatus  string         `json:"invitation_status"`
	InviteSecret      sql.NullString `json:"invite_secret"`
	InvitedAt         time.Time      `json:"invited_at"`
	AcceptedAt        sql.NullTime   `json:"accepted_at"`
}

func (q *Queries) ListSpaceMembers(ctx context.Context, spaceID string) ([]ListSpaceMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, listSpaceMembers, spaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSpaceMembersRow{}
	for rows.Next() {
		var i ListSpaceMembersRow
		if err := rows.Scan(
			&i.SpaceID,
			&i.UserID,
			&i.UserName,
			&i.UserEmail,
			&i.Role,
			&i.EncryptedSpaceKey,
			&i.InvitationStatus,
			&i.InviteSecret,
			&i.InvitedAt,
			&i.AcceptedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpacesForUser = `-- name: ListSpacesForUser :many
SELECT
    s.space_id,
    s.display_name,
    s.owner_user_id,
    s.created_at,
    s.updated_at,
    m.role,
    m.invitation_status,
    m.encrypted_space_key
FROM budget_space_members m
INNER JOIN budget_spaces s ON s.space_id = m.space_id
WHERE m.user_id = ?
ORDER BY s.created_at ASC
`

type ListSpacesForUserRow struct {
	SpaceID           string       `json:"space_id"`
	DisplayName       string       `json:"display_name"`
	OwnerUserID       string       `json:"owner_user_id"`
	CreatedAt         time.Time    `json:"created_at"`
	UpdatedAt         sql.NullTime `json:"updated_at"`
	Role              string       `json:"role"`
	InvitationStatus  string       `json:"invitation_status"`
	EncryptedSpaceKey string       `json:"encrypted_space_key"`
}

func (q *Queries) ListSpacesForUser(ctx context.Context, userID string) ([]ListSpacesForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listSpacesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSpacesForUserRow{}
	for rows.Next() {
		var i ListSpacesForUserRow
		if err := rows.Scan(
			&i.SpaceID,
			&i.DisplayName,
			&i.OwnerUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Role,
			&i.InvitationStatus,
			&i.EncryptedSpaceKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMemberEncryptedKey = `-- name: UpdateMemberEncryptedKey :exec
UPDATE budget_space_members
SET encrypted_space_key = ?, invitation_status = 'accepted', accepted_at = datetime('now')
WHERE space_id = ? AND user_id = ?
`

type UpdateMemberEncryptedKeyParams struct {
	EncryptedSpaceKey string `json:"encrypted_space_key"`
	SpaceID           string `json:"space_id"`
	UserID            string `json:"user_id"`
}

func (q *Queries) UpdateMemberEncryptedKey(ctx context.Context, arg UpdateMemberEncryptedKeyParams) error {
	_, err := q.db.ExecContext(ctx, updateMemberEncryptedKey, arg.EncryptedSpaceKey, arg.SpaceID, arg.UserID)
	return err
}

const updateMemberStatus = `-- name: UpdateMemberStatus :exec
UPDATE budget_space_members
SET invitation_status = ?, accepted_at = datetime('now')
WHERE space_id = ? AND user_id = ?
`

type UpdateMemberStatusParams struct {
	InvitationStatus string `json:"invitation_status"`
	SpaceID          string `json:"space_id"`
	UserID           string `json:"user_id"`
}

func (q *Queries) UpdateMemberStatus(ctx context.Context, arg UpdateMemberStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateMemberStatus, arg.InvitationStatus, arg.SpaceID, arg.UserID)
	return err
}
