// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: spaces.sql

package sqlc

import (
	"context"
	"time"
)

const countOccupiedCollaboratorSlotsByOwner = `-- name: CountOccupiedCollaboratorSlotsByOwner :one
SELECT
  (
    SELECT COUNT(*)
    FROM budget_space_members m
    INNER JOIN budget_spaces s ON s.space_id = m.space_id
    WHERE s.owner_user_id = ?
      AND m.role = 'member'
      AND m.invitation_status = 'accepted'
  ) + (
    SELECT COUNT(*)
    FROM budget_space_invites i
    INNER JOIN budget_spaces s ON s.space_id = i.space_id
    WHERE s.owner_user_id = ?
      AND i.status = 'pending'
      AND (? = '' OR i.id != ?)
  )
`

type CountOccupiedCollaboratorSlotsByOwnerParams struct {
	OwnerUserID   string      `json:"owner_user_id"`
	OwnerUserID_2 string      `json:"owner_user_id_2"`
	Column3       interface{} `json:"column_3"`
	ID            string      `json:"id"`
}

func (q *Queries) CountOccupiedCollaboratorSlotsByOwner(ctx context.Context, arg CountOccupiedCollaboratorSlotsByOwnerParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOccupiedCollaboratorSlotsByOwner,
		arg.OwnerUserID,
		arg.OwnerUserID_2,
		arg.Column3,
		arg.ID,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createSpace = `-- name: CreateSpace :one
INSERT INTO budget_spaces (space_id, owner_user_id, display_name, created_at)
VALUES (?, ?, ?, ?)
RETURNING space_id, owner_user_id, display_name, created_at, updated_at
`

type CreateSpaceParams struct {
	SpaceID     string    `json:"space_id"`
	OwnerUserID string    `json:"owner_user_id"`
	DisplayName string    `json:"display_name"`
	CreatedAt   time.Time `json:"created_at"`
}

func (q *Queries) CreateSpace(ctx context.Context, arg CreateSpaceParams) (BudgetSpace, error) {
	row := q.db.QueryRowContext(ctx, createSpace,
		arg.SpaceID,
		arg.OwnerUserID,
		arg.DisplayName,
		arg.CreatedAt,
	)
	var i BudgetSpace
	err := row.Scan(
		&i.SpaceID,
		&i.OwnerUserID,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSpace = `-- name: DeleteSpace :exec
DELETE FROM budget_spaces WHERE space_id = ?
`

func (q *Queries) DeleteSpace(ctx context.Context, spaceID string) error {
	_, err := q.db.ExecContext(ctx, deleteSpace, spaceID)
	return err
}

const getSpaceByID = `-- name: GetSpaceByID :one
SELECT space_id, owner_user_id, display_name, created_at, updated_at FROM budget_spaces WHERE space_id = ?
`

func (q *Queries) GetSpaceByID(ctx context.Context, spaceID string) (BudgetSpace, error) {
	row := q.db.QueryRowContext(ctx, getSpaceByID, spaceID)
	var i BudgetSpace
	err := row.Scan(
		&i.SpaceID,
		&i.OwnerUserID,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSpaceOwner = `-- name: GetSpaceOwner :one
SELECT owner_user_id FROM budget_spaces WHERE space_id = ?
`

func (q *Queries) GetSpaceOwner(ctx context.Context, spaceID string) (string, error) {
	row := q.db.QueryRowContext(ctx, getSpaceOwner, spaceID)
	var owner_user_id string
	err := row.Scan(&owner_user_id)
	return owner_user_id, err
}

const listSpacesByOwner = `-- name: ListSpacesByOwner :many
SELECT space_id, owner_user_id, display_name, created_at, updated_at FROM budget_spaces WHERE owner_user_id = ? ORDER BY created_at ASC
`

func (q *Queries) ListSpacesByOwner(ctx context.Context, ownerUserID string) ([]BudgetSpace, error) {
	rows, err := q.db.QueryContext(ctx, listSpacesByOwner, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BudgetSpace{}
	for rows.Next() {
		var i BudgetSpace
		if err := rows.Scan(
			&i.SpaceID,
			&i.OwnerUserID,
			&i.DisplayName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSpaceDisplayName = `-- name: UpdateSpaceDisplayName :exec
UPDATE budget_spaces
SET display_name = ?, updated_at = datetime('now')
WHERE space_id = ?
`

type UpdateSpaceDisplayNameParams struct {
	DisplayName string `json:"display_name"`
	SpaceID     string `json:"space_id"`
}

func (q *Queries) UpdateSpaceDisplayName(ctx context.Context, arg UpdateSpaceDisplayNameParams) error {
	_, err := q.db.ExecContext(ctx, updateSpaceDisplayName, arg.DisplayName, arg.SpaceID)
	return err
}
