// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stickiness_analytics.sql

package sqlc

import (
	"context"
	"database/sql"
)

const analyticsCohortRetention = `-- name: AnalyticsCohortRetention :many
SELECT
    strftime(?, substr(u.created_at, 1, 19)) AS cohort,
    CAST(julianday(a.day) - julianday(date(substr(u.created_at, 1, 19))) AS INTEGER) AS day_n,
    COUNT(DISTINCT a.user_id) AS active
FROM users u
JOIN user_daily_activity a ON a.user_id = u.id
WHERE u.created_at IS NOT NULL
  AND u.created_at >= ?
  AND u.email NOT LIKE '%@clerk.user'
  AND a.day >= date(substr(u.created_at, 1, 19))
  AND CAST(julianday(a.day) - julianday(date(substr(u.created_at, 1, 19))) AS INTEGER) <= CAST(? AS INTEGER)
GROUP BY cohort, day_n
ORDER BY cohort, day_n
`

type AnalyticsCohortRetentionParams struct {
	Strftime  interface{}  `json:"strftime"`
	CreatedAt sql.NullTime `json:"created_at"`
	Column3   int64        `json:"column_3"`
}

type AnalyticsCohortRetentionRow struct {
	Cohort interface{} `json:"cohort"`
	DayN   int64       `json:"day_n"`
	Active int64       `json:"active"`
}

func (q *Queries) AnalyticsCohortRetention(ctx context.Context, arg AnalyticsCohortRetentionParams) ([]AnalyticsCohortRetentionRow, error) {
	rows, err := q.db.QueryContext(ctx, analyticsCohortRetention, arg.Strftime, arg.CreatedAt, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AnalyticsCohortRetentionRow{}
	for rows.Next() {
		var i AnalyticsCohortRetentionRow
		if err := rows.Scan(&i.Cohort, &i.DayN, &i.Active); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const analyticsCohortSizes = `-- name: AnalyticsCohortSizes :many
SELECT
    strftime(?, substr(created_at, 1, 19)) AS cohort,
    COUNT(*) AS size
FROM users
WHERE created_at IS NOT NULL
  AND created_at >= ?
  AND email NOT LIKE '%@clerk.user'
GROUP BY cohort
ORDER BY cohort
`

type AnalyticsCohortSizesParams struct {
	Strftime  interface{}  `json:"strftime"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type AnalyticsCohortSizesRow struct {
	Cohort interface{} `json:"cohort"`
	Size   int64       `json:"size"`
}

func (q *Queries) AnalyticsCohortSizes(ctx context.Context, arg AnalyticsCohortSizesParams) ([]AnalyticsCohortSizesRow, error) {
	rows, err := q.db.QueryContext(ctx, analyticsCohortSizes, arg.Strftime, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AnalyticsCohortSizesRow{}
	for rows.Next() {
		var i AnalyticsCohortSizesRow
		if err := rows.Scan(&i.Cohort, &i.Size); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const analyticsDAUByDayInRange = `-- name: AnalyticsDAUByDayInRange :many

SELECT day, COUNT(DISTINCT user_id) AS dau
FROM user_daily_activity
WHERE day >= ? AND day <= ?
GROUP BY day
ORDER BY day
`

type AnalyticsDAUByDayInRangeParams struct {
	Day   string `json:"day"`
	Day_2 string `json:"day_2"`
}

type AnalyticsDAUByDayInRangeRow struct {
	Day string `json:"day"`
	Dau int64  `json:"dau"`
}

// Stickiness analytics: DAU/MAU + cohort retention.
//
// Activity source: user_daily_activity, already (user_id, day)-bucketed
// by the heartbeat handler. Day strings are stored YYYY-MM-DD so direct
// lexical comparison works.
//
// Cohort grouping uses strftime() on users.created_at. The substr() trim
// mirrors rewards_analytics.sql -- modernc.org/sqlite's t.String() bind
// format breaks strftime without it.
func (q *Queries) AnalyticsDAUByDayInRange(ctx context.Context, arg AnalyticsDAUByDayInRangeParams) ([]AnalyticsDAUByDayInRangeRow, error) {
	rows, err := q.db.QueryContext(ctx, analyticsDAUByDayInRange, arg.Day, arg.Day_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AnalyticsDAUByDayInRangeRow{}
	for rows.Next() {
		var i AnalyticsDAUByDayInRangeRow
		if err := rows.Scan(&i.Day, &i.Dau); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const analyticsMAURollingForDay = `-- name: AnalyticsMAURollingForDay :one
SELECT COUNT(DISTINCT user_id) AS mau
FROM user_daily_activity
WHERE day BETWEEN ? AND ?
`

type AnalyticsMAURollingForDayParams struct {
	FromDay string `json:"from_day"`
	ToDay   string `json:"to_day"`
}

func (q *Queries) AnalyticsMAURollingForDay(ctx context.Context, arg AnalyticsMAURollingForDayParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, analyticsMAURollingForDay, arg.FromDay, arg.ToDay)
	var mau int64
	err := row.Scan(&mau)
	return mau, err
}
