// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: trial_rewards.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const countDistinctLoggingDaysInRange = `-- name: CountDistinctLoggingDaysInRange :one
SELECT COUNT(*) AS distinct_days
FROM trial_signals
WHERE user_id = ?
  AND kind = 'daily_logging'
  AND day >= ?
  AND day <= ?
`

type CountDistinctLoggingDaysInRangeParams struct {
	UserID string `json:"user_id"`
	Day    string `json:"day"`
	Day_2  string `json:"day_2"`
}

func (q *Queries) CountDistinctLoggingDaysInRange(ctx context.Context, arg CountDistinctLoggingDaysInRangeParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDistinctLoggingDaysInRange, arg.UserID, arg.Day, arg.Day_2)
	var distinct_days int64
	err := row.Scan(&distinct_days)
	return distinct_days, err
}

const countDistinctMonthsForKind = `-- name: CountDistinctMonthsForKind :one
SELECT COUNT(*) AS total
FROM trial_signals
WHERE user_id = ?
  AND kind = ?
`

type CountDistinctMonthsForKindParams struct {
	UserID string `json:"user_id"`
	Kind   string `json:"kind"`
}

// Counts distinct rows for a kind. For the *_in_month signal kinds the
// `day` column stores YYYY-MM-01 of the month being tracked, so distinct
// rows = distinct months. For other kinds the result is "distinct days
// on which the signal fired" which isn't meaningful; callers should only
// use this for the *_in_month kinds.
func (q *Queries) CountDistinctMonthsForKind(ctx context.Context, arg CountDistinctMonthsForKindParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDistinctMonthsForKind, arg.UserID, arg.Kind)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countSignalsOfKind = `-- name: CountSignalsOfKind :one
SELECT CAST(COALESCE(SUM(count), 0) AS INTEGER) AS total
FROM trial_signals
WHERE user_id = ?
  AND kind = ?
`

type CountSignalsOfKindParams struct {
	UserID string `json:"user_id"`
	Kind   string `json:"kind"`
}

func (q *Queries) CountSignalsOfKind(ctx context.Context, arg CountSignalsOfKindParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSignalsOfKind, arg.UserID, arg.Kind)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countUserMutationsForForgeryCheck = `-- name: CountUserMutationsForForgeryCheck :one
SELECT COUNT(*) AS total
FROM mutation_log
WHERE user_id = ?
`

func (q *Queries) CountUserMutationsForForgeryCheck(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUserMutationsForForgeryCheck, userID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createDiscountCode = `-- name: CreateDiscountCode :exec
INSERT INTO trial_discount_codes (
    code, user_id, tier, percent_off, ls_discount_id,
    generated_at, valid_from, valid_until
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateDiscountCodeParams struct {
	Code         string    `json:"code"`
	UserID       string    `json:"user_id"`
	Tier         int64     `json:"tier"`
	PercentOff   int64     `json:"percent_off"`
	LsDiscountID string    `json:"ls_discount_id"`
	GeneratedAt  time.Time `json:"generated_at"`
	ValidFrom    time.Time `json:"valid_from"`
	ValidUntil   time.Time `json:"valid_until"`
}

func (q *Queries) CreateDiscountCode(ctx context.Context, arg CreateDiscountCodeParams) error {
	_, err := q.db.ExecContext(ctx, createDiscountCode,
		arg.Code,
		arg.UserID,
		arg.Tier,
		arg.PercentOff,
		arg.LsDiscountID,
		arg.GeneratedAt,
		arg.ValidFrom,
		arg.ValidUntil,
	)
	return err
}

const devDeleteTrialDiscountCodesForUser = `-- name: DevDeleteTrialDiscountCodesForUser :exec
DELETE FROM trial_discount_codes WHERE user_id = ?
`

func (q *Queries) DevDeleteTrialDiscountCodesForUser(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, devDeleteTrialDiscountCodesForUser, userID)
	return err
}

const devDeleteTrialProgressForUser = `-- name: DevDeleteTrialProgressForUser :exec
DELETE FROM trial_progress WHERE user_id = ?
`

func (q *Queries) DevDeleteTrialProgressForUser(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, devDeleteTrialProgressForUser, userID)
	return err
}

const devDeleteTrialSignalsForUser = `-- name: DevDeleteTrialSignalsForUser :exec
DELETE FROM trial_signals WHERE user_id = ?
`

func (q *Queries) DevDeleteTrialSignalsForUser(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, devDeleteTrialSignalsForUser, userID)
	return err
}

const extendDiscountCodeValidity = `-- name: ExtendDiscountCodeValidity :exec
UPDATE trial_discount_codes
SET valid_until = ?
WHERE code = ?
`

type ExtendDiscountCodeValidityParams struct {
	ValidUntil time.Time `json:"valid_until"`
	Code       string    `json:"code"`
}

func (q *Queries) ExtendDiscountCodeValidity(ctx context.Context, arg ExtendDiscountCodeValidityParams) error {
	_, err := q.db.ExecContext(ctx, extendDiscountCodeValidity, arg.ValidUntil, arg.Code)
	return err
}

const getDiscountCodeByCode = `-- name: GetDiscountCodeByCode :one
SELECT
    code, user_id, tier, percent_off, ls_discount_id,
    generated_at, valid_from, valid_until, redeemed_at, redeemed_sub_id
FROM trial_discount_codes
WHERE code = ?
`

func (q *Queries) GetDiscountCodeByCode(ctx context.Context, code string) (TrialDiscountCode, error) {
	row := q.db.QueryRowContext(ctx, getDiscountCodeByCode, code)
	var i TrialDiscountCode
	err := row.Scan(
		&i.Code,
		&i.UserID,
		&i.Tier,
		&i.PercentOff,
		&i.LsDiscountID,
		&i.GeneratedAt,
		&i.ValidFrom,
		&i.ValidUntil,
		&i.RedeemedAt,
		&i.RedeemedSubID,
	)
	return i, err
}

const getDiscountCodeByUserTier = `-- name: GetDiscountCodeByUserTier :one
SELECT
    code, user_id, tier, percent_off, ls_discount_id,
    generated_at, valid_from, valid_until, redeemed_at, redeemed_sub_id
FROM trial_discount_codes
WHERE user_id = ? AND tier = ?
`

type GetDiscountCodeByUserTierParams struct {
	UserID string `json:"user_id"`
	Tier   int64  `json:"tier"`
}

func (q *Queries) GetDiscountCodeByUserTier(ctx context.Context, arg GetDiscountCodeByUserTierParams) (TrialDiscountCode, error) {
	row := q.db.QueryRowContext(ctx, getDiscountCodeByUserTier, arg.UserID, arg.Tier)
	var i TrialDiscountCode
	err := row.Scan(
		&i.Code,
		&i.UserID,
		&i.Tier,
		&i.PercentOff,
		&i.LsDiscountID,
		&i.GeneratedAt,
		&i.ValidFrom,
		&i.ValidUntil,
		&i.RedeemedAt,
		&i.RedeemedSubID,
	)
	return i, err
}

const getEarliestSignalAt = `-- name: GetEarliestSignalAt :one
SELECT first_at
FROM trial_signals
WHERE user_id = ?
  AND kind = ?
ORDER BY first_at ASC
LIMIT 1
`

type GetEarliestSignalAtParams struct {
	UserID string `json:"user_id"`
	Kind   string `json:"kind"`
}

func (q *Queries) GetEarliestSignalAt(ctx context.Context, arg GetEarliestSignalAtParams) (time.Time, error) {
	row := q.db.QueryRowContext(ctx, getEarliestSignalAt, arg.UserID, arg.Kind)
	var first_at time.Time
	err := row.Scan(&first_at)
	return first_at, err
}

const getNthSignalAt = `-- name: GetNthSignalAt :one
SELECT first_at
FROM trial_signals
WHERE user_id = ?
  AND kind = ?
ORDER BY first_at ASC
LIMIT 1 OFFSET ?
`

type GetNthSignalAtParams struct {
	UserID string `json:"user_id"`
	Kind   string `json:"kind"`
	Offset int64  `json:"offset"`
}

func (q *Queries) GetNthSignalAt(ctx context.Context, arg GetNthSignalAtParams) (time.Time, error) {
	row := q.db.QueryRowContext(ctx, getNthSignalAt, arg.UserID, arg.Kind, arg.Offset)
	var first_at time.Time
	err := row.Scan(&first_at)
	return first_at, err
}

const getTrialProgress = `-- name: GetTrialProgress :one
SELECT
    user_id,
    trial_started_at,
    daily_logging_distinct_days,
    reconciliation_count,
    first_reconciliation_at,
    second_reconciliation_at,
    budget_cycle_assigned_at,
    overspend_covered_at,
    goal_funded_at,
    rule_applied_historical_at,
    monthly_review_at,
    tier1_unlocked_at,
    tier2_unlocked_at,
    tier3_unlocked_at,
    updated_at
FROM trial_progress
WHERE user_id = ?
`

func (q *Queries) GetTrialProgress(ctx context.Context, userID string) (TrialProgress, error) {
	row := q.db.QueryRowContext(ctx, getTrialProgress, userID)
	var i TrialProgress
	err := row.Scan(
		&i.UserID,
		&i.TrialStartedAt,
		&i.DailyLoggingDistinctDays,
		&i.ReconciliationCount,
		&i.FirstReconciliationAt,
		&i.SecondReconciliationAt,
		&i.BudgetCycleAssignedAt,
		&i.OverspendCoveredAt,
		&i.GoalFundedAt,
		&i.RuleAppliedHistoricalAt,
		&i.MonthlyReviewAt,
		&i.Tier1UnlockedAt,
		&i.Tier2UnlockedAt,
		&i.Tier3UnlockedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDiscountCodesByUser = `-- name: ListDiscountCodesByUser :many
SELECT
    code, user_id, tier, percent_off, ls_discount_id,
    generated_at, valid_from, valid_until, redeemed_at, redeemed_sub_id
FROM trial_discount_codes
WHERE user_id = ?
ORDER BY tier ASC
`

func (q *Queries) ListDiscountCodesByUser(ctx context.Context, userID string) ([]TrialDiscountCode, error) {
	rows, err := q.db.QueryContext(ctx, listDiscountCodesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TrialDiscountCode{}
	for rows.Next() {
		var i TrialDiscountCode
		if err := rows.Scan(
			&i.Code,
			&i.UserID,
			&i.Tier,
			&i.PercentOff,
			&i.LsDiscountID,
			&i.GeneratedAt,
			&i.ValidFrom,
			&i.ValidUntil,
			&i.RedeemedAt,
			&i.RedeemedSubID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDiscountCodeRedeemed = `-- name: MarkDiscountCodeRedeemed :exec
UPDATE trial_discount_codes
SET redeemed_at = ?, redeemed_sub_id = ?
WHERE code = ? AND redeemed_at IS NULL
`

type MarkDiscountCodeRedeemedParams struct {
	RedeemedAt    sql.NullTime   `json:"redeemed_at"`
	RedeemedSubID sql.NullString `json:"redeemed_sub_id"`
	Code          string         `json:"code"`
}

func (q *Queries) MarkDiscountCodeRedeemed(ctx context.Context, arg MarkDiscountCodeRedeemedParams) error {
	_, err := q.db.ExecContext(ctx, markDiscountCodeRedeemed, arg.RedeemedAt, arg.RedeemedSubID, arg.Code)
	return err
}

const upsertTrialProgress = `-- name: UpsertTrialProgress :exec
INSERT INTO trial_progress (
    user_id,
    trial_started_at,
    daily_logging_distinct_days,
    reconciliation_count,
    first_reconciliation_at,
    second_reconciliation_at,
    budget_cycle_assigned_at,
    overspend_covered_at,
    goal_funded_at,
    rule_applied_historical_at,
    monthly_review_at,
    tier1_unlocked_at,
    tier2_unlocked_at,
    tier3_unlocked_at,
    updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(user_id) DO UPDATE SET
    daily_logging_distinct_days = excluded.daily_logging_distinct_days,
    reconciliation_count        = excluded.reconciliation_count,
    first_reconciliation_at     = COALESCE(trial_progress.first_reconciliation_at, excluded.first_reconciliation_at),
    second_reconciliation_at    = COALESCE(trial_progress.second_reconciliation_at, excluded.second_reconciliation_at),
    budget_cycle_assigned_at    = COALESCE(trial_progress.budget_cycle_assigned_at, excluded.budget_cycle_assigned_at),
    overspend_covered_at        = COALESCE(trial_progress.overspend_covered_at, excluded.overspend_covered_at),
    goal_funded_at              = COALESCE(trial_progress.goal_funded_at, excluded.goal_funded_at),
    rule_applied_historical_at  = COALESCE(trial_progress.rule_applied_historical_at, excluded.rule_applied_historical_at),
    monthly_review_at           = COALESCE(trial_progress.monthly_review_at, excluded.monthly_review_at),
    tier1_unlocked_at           = COALESCE(trial_progress.tier1_unlocked_at, excluded.tier1_unlocked_at),
    tier2_unlocked_at           = COALESCE(trial_progress.tier2_unlocked_at, excluded.tier2_unlocked_at),
    tier3_unlocked_at           = COALESCE(trial_progress.tier3_unlocked_at, excluded.tier3_unlocked_at),
    updated_at                  = excluded.updated_at
`

type UpsertTrialProgressParams struct {
	UserID                   string       `json:"user_id"`
	TrialStartedAt           time.Time    `json:"trial_started_at"`
	DailyLoggingDistinctDays int64        `json:"daily_logging_distinct_days"`
	ReconciliationCount      int64        `json:"reconciliation_count"`
	FirstReconciliationAt    sql.NullTime `json:"first_reconciliation_at"`
	SecondReconciliationAt   sql.NullTime `json:"second_reconciliation_at"`
	BudgetCycleAssignedAt    sql.NullTime `json:"budget_cycle_assigned_at"`
	OverspendCoveredAt       sql.NullTime `json:"overspend_covered_at"`
	GoalFundedAt             sql.NullTime `json:"goal_funded_at"`
	RuleAppliedHistoricalAt  sql.NullTime `json:"rule_applied_historical_at"`
	MonthlyReviewAt          sql.NullTime `json:"monthly_review_at"`
	Tier1UnlockedAt          sql.NullTime `json:"tier1_unlocked_at"`
	Tier2UnlockedAt          sql.NullTime `json:"tier2_unlocked_at"`
	Tier3UnlockedAt          sql.NullTime `json:"tier3_unlocked_at"`
	UpdatedAt                time.Time    `json:"updated_at"`
}

func (q *Queries) UpsertTrialProgress(ctx context.Context, arg UpsertTrialProgressParams) error {
	_, err := q.db.ExecContext(ctx, upsertTrialProgress,
		arg.UserID,
		arg.TrialStartedAt,
		arg.DailyLoggingDistinctDays,
		arg.ReconciliationCount,
		arg.FirstReconciliationAt,
		arg.SecondReconciliationAt,
		arg.BudgetCycleAssignedAt,
		arg.OverspendCoveredAt,
		arg.GoalFundedAt,
		arg.RuleAppliedHistoricalAt,
		arg.MonthlyReviewAt,
		arg.Tier1UnlockedAt,
		arg.Tier2UnlockedAt,
		arg.Tier3UnlockedAt,
		arg.UpdatedAt,
	)
	return err
}

const upsertTrialSignal = `-- name: UpsertTrialSignal :exec
INSERT INTO trial_signals (
    user_id, kind, day, count, first_at, last_at
) VALUES (?, ?, ?, 1, ?, ?)
ON CONFLICT(user_id, kind, day) DO UPDATE SET
    count   = trial_signals.count + 1,
    last_at = excluded.last_at
`

type UpsertTrialSignalParams struct {
	UserID  string    `json:"user_id"`
	Kind    string    `json:"kind"`
	Day     string    `json:"day"`
	FirstAt time.Time `json:"first_at"`
	LastAt  time.Time `json:"last_at"`
}

func (q *Queries) UpsertTrialSignal(ctx context.Context, arg UpsertTrialSignalParams) error {
	_, err := q.db.ExecContext(ctx, upsertTrialSignal,
		arg.UserID,
		arg.Kind,
		arg.Day,
		arg.FirstAt,
		arg.LastAt,
	)
	return err
}
