// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"
	"database/sql"
)

const backfillTrialForInactiveUsers = `-- name: BackfillTrialForInactiveUsers :execresult
UPDATE users
SET subscription_status = 'trialing',
    trial_ends_at = datetime(created_at, '+' || ? || ' days')
WHERE subscription_status = 'inactive'
AND trial_ends_at IS NULL
`

func (q *Queries) BackfillTrialForInactiveUsers(ctx context.Context, dollar_1 sql.NullString) (sql.Result, error) {
	return q.db.ExecContext(ctx, backfillTrialForInactiveUsers, dollar_1)
}

const blockUser = `-- name: BlockUser :exec
UPDATE users SET is_blocked = ? WHERE id = ?
`

type BlockUserParams struct {
	IsBlocked bool   `json:"is_blocked"`
	ID        string `json:"id"`
}

func (q *Queries) BlockUser(ctx context.Context, arg BlockUserParams) error {
	_, err := q.db.ExecContext(ctx, blockUser, arg.IsBlocked, arg.ID)
	return err
}

const clearDanglingPrimarySpaceIDs = `-- name: ClearDanglingPrimarySpaceIDs :exec
UPDATE users SET primary_space_id = NULL
WHERE primary_space_id IS NOT NULL
AND primary_space_id NOT IN (SELECT space_id FROM budget_spaces)
`

func (q *Queries) ClearDanglingPrimarySpaceIDs(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearDanglingPrimarySpaceIDs)
	return err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    id, name, email, db_path, is_master_password_set,
    subscription_status, trial_ends_at, created_at, primary_space_id,
    current_db_hash, sync_version, is_analytics_disabled
) VALUES (?, ?, ?, '', 0, ?, ?, ?, NULL, '', 0, 1)
RETURNING id, name, email, db_path, is_master_password_set, current_db_hash, sync_version, created_at, last_user_db_backup, backup_reminder_frequency_days, is_blocked, subscription_status, subscription_id, customer_id, variant_id, subscription_ends_at, trial_ends_at, current_period_end, has_beta_access, beta_expires_at, is_founding_member, has_collaboration_access, onboarding_status, onboarding_completed_at, onboarding_snoozed_until, primary_space_id, is_analytics_disabled, subscribed_at, where_heard_about, is_trial_signals_disabled
`

type CreateUserParams struct {
	ID                 string         `json:"id"`
	Name               string         `json:"name"`
	Email              string         `json:"email"`
	SubscriptionStatus sql.NullString `json:"subscription_status"`
	TrialEndsAt        sql.NullTime   `json:"trial_ends_at"`
	CreatedAt          sql.NullTime   `json:"created_at"`
}

// Analytics is OPT-IN: new users start with analytics disabled and must
// enable it explicitly in Settings (the column's legacy DEFAULT 0 predates
// the opt-in policy and only governs pre-existing rows).
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.SubscriptionStatus,
		arg.TrialEndsAt,
		arg.CreatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.DbPath,
		&i.IsMasterPasswordSet,
		&i.CurrentDbHash,
		&i.SyncVersion,
		&i.CreatedAt,
		&i.LastUserDbBackup,
		&i.BackupReminderFrequencyDays,
		&i.IsBlocked,
		&i.SubscriptionStatus,
		&i.SubscriptionID,
		&i.CustomerID,
		&i.VariantID,
		&i.SubscriptionEndsAt,
		&i.TrialEndsAt,
		&i.CurrentPeriodEnd,
		&i.HasBetaAccess,
		&i.BetaExpiresAt,
		&i.IsFoundingMember,
		&i.HasCollaborationAccess,
		&i.OnboardingStatus,
		&i.OnboardingCompletedAt,
		&i.OnboardingSnoozedUntil,
		&i.PrimarySpaceID,
		&i.IsAnalyticsDisabled,
		&i.SubscribedAt,
		&i.WhereHeardAbout,
		&i.IsTrialSignalsDisabled,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getUserByCustomerID = `-- name: GetUserByCustomerID :one
SELECT id, name, email, db_path, is_master_password_set, current_db_hash, sync_version, created_at, last_user_db_backup, backup_reminder_frequency_days, is_blocked, subscription_status, subscription_id, customer_id, variant_id, subscription_ends_at, trial_ends_at, current_period_end, has_beta_access, beta_expires_at, is_founding_member, has_collaboration_access, onboarding_status, onboarding_completed_at, onboarding_snoozed_until, primary_space_id, is_analytics_disabled, subscribed_at, where_heard_about, is_trial_signals_disabled FROM users WHERE customer_id = ?
`

func (q *Queries) GetUserByCustomerID(ctx context.Context, customerID sql.NullString) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByCustomerID, customerID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.DbPath,
		&i.IsMasterPasswordSet,
		&i.CurrentDbHash,
		&i.SyncVersion,
		&i.CreatedAt,
		&i.LastUserDbBackup,
		&i.BackupReminderFrequencyDays,
		&i.IsBlocked,
		&i.SubscriptionStatus,
		&i.SubscriptionID,
		&i.CustomerID,
		&i.VariantID,
		&i.SubscriptionEndsAt,
		&i.TrialEndsAt,
		&i.CurrentPeriodEnd,
		&i.HasBetaAccess,
		&i.BetaExpiresAt,
		&i.IsFoundingMember,
		&i.HasCollaborationAccess,
		&i.OnboardingStatus,
		&i.OnboardingCompletedAt,
		&i.OnboardingSnoozedUntil,
		&i.PrimarySpaceID,
		&i.IsAnalyticsDisabled,
		&i.SubscribedAt,
		&i.WhereHeardAbout,
		&i.IsTrialSignalsDisabled,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, db_path, is_master_password_set, current_db_hash, sync_version, created_at, last_user_db_backup, backup_reminder_frequency_days, is_blocked, subscription_status, subscription_id, customer_id, variant_id, subscription_ends_at, trial_ends_at, current_period_end, has_beta_access, beta_expires_at, is_founding_member, has_collaboration_access, onboarding_status, onboarding_completed_at, onboarding_snoozed_until, primary_space_id, is_analytics_disabled, subscribed_at, where_heard_about, is_trial_signals_disabled FROM users WHERE email = ?
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.DbPath,
		&i.IsMasterPasswordSet,
		&i.CurrentDbHash,
		&i.SyncVersion,
		&i.CreatedAt,
		&i.LastUserDbBackup,
		&i.BackupReminderFrequencyDays,
		&i.IsBlocked,
		&i.SubscriptionStatus,
		&i.SubscriptionID,
		&i.CustomerID,
		&i.VariantID,
		&i.SubscriptionEndsAt,
		&i.TrialEndsAt,
		&i.CurrentPeriodEnd,
		&i.HasBetaAccess,
		&i.BetaExpiresAt,
		&i.IsFoundingMember,
		&i.HasCollaborationAccess,
		&i.OnboardingStatus,
		&i.OnboardingCompletedAt,
		&i.OnboardingSnoozedUntil,
		&i.PrimarySpaceID,
		&i.IsAnalyticsDisabled,
		&i.SubscribedAt,
		&i.WhereHeardAbout,
		&i.IsTrialSignalsDisabled,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, email, db_path, is_master_password_set, current_db_hash, sync_version, created_at, last_user_db_backup, backup_reminder_frequency_days, is_blocked, subscription_status, subscription_id, customer_id, variant_id, subscription_ends_at, trial_ends_at, current_period_end, has_beta_access, beta_expires_at, is_founding_member, has_collaboration_access, onboarding_status, onboarding_completed_at, onboarding_snoozed_until, primary_space_id, is_analytics_disabled, subscribed_at, where_heard_about, is_trial_signals_disabled FROM users WHERE id = ?
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.DbPath,
		&i.IsMasterPasswordSet,
		&i.CurrentDbHash,
		&i.SyncVersion,
		&i.CreatedAt,
		&i.LastUserDbBackup,
		&i.BackupReminderFrequencyDays,
		&i.IsBlocked,
		&i.SubscriptionStatus,
		&i.SubscriptionID,
		&i.CustomerID,
		&i.VariantID,
		&i.SubscriptionEndsAt,
		&i.TrialEndsAt,
		&i.CurrentPeriodEnd,
		&i.HasBetaAccess,
		&i.BetaExpiresAt,
		&i.IsFoundingMember,
		&i.HasCollaborationAccess,
		&i.OnboardingStatus,
		&i.OnboardingCompletedAt,
		&i.OnboardingSnoozedUntil,
		&i.PrimarySpaceID,
		&i.IsAnalyticsDisabled,
		&i.SubscribedAt,
		&i.WhereHeardAbout,
		&i.IsTrialSignalsDisabled,
	)
	return i, err
}

const grantBetaAccess = `-- name: GrantBetaAccess :exec
UPDATE users SET has_beta_access = 1, beta_expires_at = ? WHERE id = ?
`

type GrantBetaAccessParams struct {
	BetaExpiresAt sql.NullTime `json:"beta_expires_at"`
	ID            string       `json:"id"`
}

func (q *Queries) GrantBetaAccess(ctx context.Context, arg GrantBetaAccessParams) error {
	_, err := q.db.ExecContext(ctx, grantBetaAccess, arg.BetaExpiresAt, arg.ID)
	return err
}

const grantFoundingMemberAccess = `-- name: GrantFoundingMemberAccess :exec
UPDATE users
SET is_founding_member = 1, has_beta_access = 0, beta_expires_at = NULL
WHERE id = ?
`

func (q *Queries) GrantFoundingMemberAccess(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, grantFoundingMemberAccess, id)
	return err
}

const isUserBlocked = `-- name: IsUserBlocked :one
SELECT is_blocked FROM users WHERE id = ?
`

func (q *Queries) IsUserBlocked(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRowContext(ctx, isUserBlocked, id)
	var is_blocked bool
	err := row.Scan(&is_blocked)
	return is_blocked, err
}

const listAllUsers = `-- name: ListAllUsers :many
SELECT id, name, email, db_path, is_master_password_set, current_db_hash, sync_version, created_at, last_user_db_backup, backup_reminder_frequency_days, is_blocked, subscription_status, subscription_id, customer_id, variant_id, subscription_ends_at, trial_ends_at, current_period_end, has_beta_access, beta_expires_at, is_founding_member, has_collaboration_access, onboarding_status, onboarding_completed_at, onboarding_snoozed_until, primary_space_id, is_analytics_disabled, subscribed_at, where_heard_about, is_trial_signals_disabled FROM users ORDER BY created_at DESC
`

func (q *Queries) ListAllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.DbPath,
			&i.IsMasterPasswordSet,
			&i.CurrentDbHash,
			&i.SyncVersion,
			&i.CreatedAt,
			&i.LastUserDbBackup,
			&i.BackupReminderFrequencyDays,
			&i.IsBlocked,
			&i.SubscriptionStatus,
			&i.SubscriptionID,
			&i.CustomerID,
			&i.VariantID,
			&i.SubscriptionEndsAt,
			&i.TrialEndsAt,
			&i.CurrentPeriodEnd,
			&i.HasBetaAccess,
			&i.BetaExpiresAt,
			&i.IsFoundingMember,
			&i.HasCollaborationAccess,
			&i.OnboardingStatus,
			&i.OnboardingCompletedAt,
			&i.OnboardingSnoozedUntil,
			&i.PrimarySpaceID,
			&i.IsAnalyticsDisabled,
			&i.SubscribedAt,
			&i.WhereHeardAbout,
			&i.IsTrialSignalsDisabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markUserSubscribedIfFirstTime = `-- name: MarkUserSubscribedIfFirstTime :exec
UPDATE users SET subscribed_at = ? WHERE id = ? AND subscribed_at IS NULL
`

type MarkUserSubscribedIfFirstTimeParams struct {
	SubscribedAt sql.NullTime `json:"subscribed_at"`
	ID           string       `json:"id"`
}

// Sets users.subscribed_at = ? only when the column is currently NULL.
// Called from the subscription_created webhook handler to capture the
// user's first paid transition; renewals are no-ops here.
func (q *Queries) MarkUserSubscribedIfFirstTime(ctx context.Context, arg MarkUserSubscribedIfFirstTimeParams) error {
	_, err := q.db.ExecContext(ctx, markUserSubscribedIfFirstTime, arg.SubscribedAt, arg.ID)
	return err
}

const resetUserData = `-- name: ResetUserData :exec
UPDATE users
SET is_master_password_set = 0,
    current_db_hash = '',
    sync_version = 0,
    onboarding_status = 'pending',
    onboarding_completed_at = NULL,
    onboarding_snoozed_until = NULL,
    primary_space_id = NULL
WHERE id = ?
`

func (q *Queries) ResetUserData(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, resetUserData, id)
	return err
}

const revokeBetaAccess = `-- name: RevokeBetaAccess :exec
UPDATE users SET has_beta_access = 0, beta_expires_at = NULL WHERE id = ?
`

func (q *Queries) RevokeBetaAccess(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, revokeBetaAccess, id)
	return err
}

const setAnalyticsDisabled = `-- name: SetAnalyticsDisabled :exec
UPDATE users SET is_analytics_disabled = ? WHERE id = ?
`

type SetAnalyticsDisabledParams struct {
	IsAnalyticsDisabled bool   `json:"is_analytics_disabled"`
	ID                  string `json:"id"`
}

func (q *Queries) SetAnalyticsDisabled(ctx context.Context, arg SetAnalyticsDisabledParams) error {
	_, err := q.db.ExecContext(ctx, setAnalyticsDisabled, arg.IsAnalyticsDisabled, arg.ID)
	return err
}

const setCollaborationAccess = `-- name: SetCollaborationAccess :exec
UPDATE users SET has_collaboration_access = ? WHERE id = ?
`

type SetCollaborationAccessParams struct {
	HasCollaborationAccess bool   `json:"has_collaboration_access"`
	ID                     string `json:"id"`
}

func (q *Queries) SetCollaborationAccess(ctx context.Context, arg SetCollaborationAccessParams) error {
	_, err := q.db.ExecContext(ctx, setCollaborationAccess, arg.HasCollaborationAccess, arg.ID)
	return err
}

const setMasterPasswordStatus = `-- name: SetMasterPasswordStatus :exec
UPDATE users SET is_master_password_set = ? WHERE id = ?
`

type SetMasterPasswordStatusParams struct {
	IsMasterPasswordSet bool   `json:"is_master_password_set"`
	ID                  string `json:"id"`
}

func (q *Queries) SetMasterPasswordStatus(ctx context.Context, arg SetMasterPasswordStatusParams) error {
	_, err := q.db.ExecContext(ctx, setMasterPasswordStatus, arg.IsMasterPasswordSet, arg.ID)
	return err
}

const setOnboardingState = `-- name: SetOnboardingState :exec
UPDATE users
SET onboarding_status = ?, onboarding_completed_at = ?, onboarding_snoozed_until = ?
WHERE id = ?
`

type SetOnboardingStateParams struct {
	OnboardingStatus       string       `json:"onboarding_status"`
	OnboardingCompletedAt  sql.NullTime `json:"onboarding_completed_at"`
	OnboardingSnoozedUntil sql.NullTime `json:"onboarding_snoozed_until"`
	ID                     string       `json:"id"`
}

func (q *Queries) SetOnboardingState(ctx context.Context, arg SetOnboardingStateParams) error {
	_, err := q.db.ExecContext(ctx, setOnboardingState,
		arg.OnboardingStatus,
		arg.OnboardingCompletedAt,
		arg.OnboardingSnoozedUntil,
		arg.ID,
	)
	return err
}

const setReferralSource = `-- name: SetReferralSource :exec
UPDATE users SET where_heard_about = ? WHERE id = ?
`

type SetReferralSourceParams struct {
	WhereHeardAbout string `json:"where_heard_about"`
	ID              string `json:"id"`
}

// Records how the user discovered Budgero (onboarding "How did you hear about
// us?" step). Only written when the user provides a non-empty answer.
func (q *Queries) SetReferralSource(ctx context.Context, arg SetReferralSourceParams) error {
	_, err := q.db.ExecContext(ctx, setReferralSource, arg.WhereHeardAbout, arg.ID)
	return err
}

const setTrialSignalsDisabled = `-- name: SetTrialSignalsDisabled :exec
UPDATE users SET is_trial_signals_disabled = ? WHERE id = ?
`

type SetTrialSignalsDisabledParams struct {
	IsTrialSignalsDisabled bool   `json:"is_trial_signals_disabled"`
	ID                     string `json:"id"`
}

func (q *Queries) SetTrialSignalsDisabled(ctx context.Context, arg SetTrialSignalsDisabledParams) error {
	_, err := q.db.ExecContext(ctx, setTrialSignalsDisabled, arg.IsTrialSignalsDisabled, arg.ID)
	return err
}

const updateBackupSettings = `-- name: UpdateBackupSettings :exec
UPDATE users
SET backup_reminder_frequency_days = ?, last_user_db_backup = ?
WHERE id = ?
`

type UpdateBackupSettingsParams struct {
	BackupReminderFrequencyDays int64        `json:"backup_reminder_frequency_days"`
	LastUserDbBackup            sql.NullTime `json:"last_user_db_backup"`
	ID                          string       `json:"id"`
}

func (q *Queries) UpdateBackupSettings(ctx context.Context, arg UpdateBackupSettingsParams) error {
	_, err := q.db.ExecContext(ctx, updateBackupSettings, arg.BackupReminderFrequencyDays, arg.LastUserDbBackup, arg.ID)
	return err
}

const updateSubscription = `-- name: UpdateSubscription :exec
UPDATE users
SET subscription_status = ?, subscription_id = ?, customer_id = ?,
    variant_id = ?, subscription_ends_at = ?, current_period_end = ?, trial_ends_at = ?
WHERE id = ?
`

type UpdateSubscriptionParams struct {
	SubscriptionStatus sql.NullString `json:"subscription_status"`
	SubscriptionID     sql.NullString `json:"subscription_id"`
	CustomerID         sql.NullString `json:"customer_id"`
	VariantID          sql.NullString `json:"variant_id"`
	SubscriptionEndsAt sql.NullTime   `json:"subscription_ends_at"`
	CurrentPeriodEnd   sql.NullTime   `json:"current_period_end"`
	TrialEndsAt        sql.NullTime   `json:"trial_ends_at"`
	ID                 string         `json:"id"`
}

func (q *Queries) UpdateSubscription(ctx context.Context, arg UpdateSubscriptionParams) error {
	_, err := q.db.ExecContext(ctx, updateSubscription,
		arg.SubscriptionStatus,
		arg.SubscriptionID,
		arg.CustomerID,
		arg.VariantID,
		arg.SubscriptionEndsAt,
		arg.CurrentPeriodEnd,
		arg.TrialEndsAt,
		arg.ID,
	)
	return err
}

const updateSubscriptionAfterResume = `-- name: UpdateSubscriptionAfterResume :exec
UPDATE users
SET subscription_status = ?, subscription_ends_at = NULL,
    current_period_end = ?, variant_id = ?, trial_ends_at = ?
WHERE id = ?
`

type UpdateSubscriptionAfterResumeParams struct {
	SubscriptionStatus sql.NullString `json:"subscription_status"`
	CurrentPeriodEnd   sql.NullTime   `json:"current_period_end"`
	VariantID          sql.NullString `json:"variant_id"`
	TrialEndsAt        sql.NullTime   `json:"trial_ends_at"`
	ID                 string         `json:"id"`
}

func (q *Queries) UpdateSubscriptionAfterResume(ctx context.Context, arg UpdateSubscriptionAfterResumeParams) error {
	_, err := q.db.ExecContext(ctx, updateSubscriptionAfterResume,
		arg.SubscriptionStatus,
		arg.CurrentPeriodEnd,
		arg.VariantID,
		arg.TrialEndsAt,
		arg.ID,
	)
	return err
}

const updateSubscriptionStatus = `-- name: UpdateSubscriptionStatus :exec
UPDATE users
SET subscription_status = ?, subscription_ends_at = ?, current_period_end = ?
WHERE id = ?
`

type UpdateSubscriptionStatusParams struct {
	SubscriptionStatus sql.NullString `json:"subscription_status"`
	SubscriptionEndsAt sql.NullTime   `json:"subscription_ends_at"`
	CurrentPeriodEnd   sql.NullTime   `json:"current_period_end"`
	ID                 string         `json:"id"`
}

func (q *Queries) UpdateSubscriptionStatus(ctx context.Context, arg UpdateSubscriptionStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateSubscriptionStatus,
		arg.SubscriptionStatus,
		arg.SubscriptionEndsAt,
		arg.CurrentPeriodEnd,
		arg.ID,
	)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users SET name = ?, email = ? WHERE id = ?
`

type UpdateUserParams struct {
	Name  string `json:"name"`
	Email string `json:"email"`
	ID    string `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser, arg.Name, arg.Email, arg.ID)
	return err
}

const updateUserPrimarySpace = `-- name: UpdateUserPrimarySpace :exec
UPDATE users SET primary_space_id = ? WHERE id = ?
`

type UpdateUserPrimarySpaceParams struct {
	PrimarySpaceID sql.NullString `json:"primary_space_id"`
	ID             string         `json:"id"`
}

func (q *Queries) UpdateUserPrimarySpace(ctx context.Context, arg UpdateUserPrimarySpaceParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPrimarySpace, arg.PrimarySpaceID, arg.ID)
	return err
}
