// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_preferences.sql

package sqlc

import (
	"context"
)

const getUserPreferences = `-- name: GetUserPreferences :one
SELECT user_id, theme_mode, theme_preset, classic_font, home_page, desktop_budget_layout, compact_mobile_layout, mobile_budget_layout, created_at, updated_at, master_password_storage_mode, master_password_storage_days FROM user_preferences WHERE user_id = ?
`

func (q *Queries) GetUserPreferences(ctx context.Context, userID string) (UserPreference, error) {
	row := q.db.QueryRowContext(ctx, getUserPreferences, userID)
	var i UserPreference
	err := row.Scan(
		&i.UserID,
		&i.ThemeMode,
		&i.ThemePreset,
		&i.ClassicFont,
		&i.HomePage,
		&i.DesktopBudgetLayout,
		&i.CompactMobileLayout,
		&i.MobileBudgetLayout,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MasterPasswordStorageMode,
		&i.MasterPasswordStorageDays,
	)
	return i, err
}

const upsertUserPreferences = `-- name: UpsertUserPreferences :exec
INSERT INTO user_preferences (
    user_id,
    theme_mode,
    theme_preset,
    classic_font,
    home_page,
    desktop_budget_layout,
    compact_mobile_layout,
    mobile_budget_layout,
    master_password_storage_mode,
    master_password_storage_days
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(user_id) DO UPDATE SET
    theme_mode = excluded.theme_mode,
    theme_preset = excluded.theme_preset,
    classic_font = excluded.classic_font,
    home_page = excluded.home_page,
    desktop_budget_layout = excluded.desktop_budget_layout,
    compact_mobile_layout = excluded.compact_mobile_layout,
    mobile_budget_layout = excluded.mobile_budget_layout,
    master_password_storage_mode = excluded.master_password_storage_mode,
    master_password_storage_days = excluded.master_password_storage_days,
    updated_at = datetime('now')
`

type UpsertUserPreferencesParams struct {
	UserID                    string `json:"user_id"`
	ThemeMode                 string `json:"theme_mode"`
	ThemePreset               string `json:"theme_preset"`
	ClassicFont               string `json:"classic_font"`
	HomePage                  string `json:"home_page"`
	DesktopBudgetLayout       string `json:"desktop_budget_layout"`
	CompactMobileLayout       bool   `json:"compact_mobile_layout"`
	MobileBudgetLayout        string `json:"mobile_budget_layout"`
	MasterPasswordStorageMode string `json:"master_password_storage_mode"`
	MasterPasswordStorageDays int64  `json:"master_password_storage_days"`
}

func (q *Queries) UpsertUserPreferences(ctx context.Context, arg UpsertUserPreferencesParams) error {
	_, err := q.db.ExecContext(ctx, upsertUserPreferences,
		arg.UserID,
		arg.ThemeMode,
		arg.ThemePreset,
		arg.ClassicFont,
		arg.HomePage,
		arg.DesktopBudgetLayout,
		arg.CompactMobileLayout,
		arg.MobileBudgetLayout,
		arg.MasterPasswordStorageMode,
		arg.MasterPasswordStorageDays,
	)
	return err
}
