// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_feedback.sql

package sqlc

import (
	"context"
	"time"
)

const insertUserFeedback = `-- name: InsertUserFeedback :exec
INSERT INTO user_feedback (
    id, user_id, category, body, contact_back,
    screen_path, app_version, user_agent, created_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertUserFeedbackParams struct {
	ID          string    `json:"id"`
	UserID      string    `json:"user_id"`
	Category    string    `json:"category"`
	Body        string    `json:"body"`
	ContactBack bool      `json:"contact_back"`
	ScreenPath  string    `json:"screen_path"`
	AppVersion  string    `json:"app_version"`
	UserAgent   string    `json:"user_agent"`
	CreatedAt   time.Time `json:"created_at"`
}

func (q *Queries) InsertUserFeedback(ctx context.Context, arg InsertUserFeedbackParams) error {
	_, err := q.db.ExecContext(ctx, insertUserFeedback,
		arg.ID,
		arg.UserID,
		arg.Category,
		arg.Body,
		arg.ContactBack,
		arg.ScreenPath,
		arg.AppVersion,
		arg.UserAgent,
		arg.CreatedAt,
	)
	return err
}
